/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/ExMonster.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_ExMonsterBase : public EntityCall
{
public:

	EntityBaseEntityCall_ExMonsterBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_ExMonsterBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_ExMonsterBase : public EntityCall
{
public:

	EntityCellEntityCall_ExMonsterBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_ExMonsterBase();
	void AnimUpdate(const ANIM_INFO& arg1);
	void Attack(const SKILL_INFO& arg1);
	void Relive();
};

}