/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/ExRoomMgr.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_ExRoomMgrBase : public EntityCall
{
public:

	EntityBaseEntityCall_ExRoomMgrBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_ExRoomMgrBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_ExRoomMgrBase : public EntityCall
{
public:

	EntityCellEntityCall_ExRoomMgrBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_ExRoomMgrBase();
};

}