/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/ExGate.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_ExGateBase : public EntityCall
{
public:

	EntityBaseEntityCall_ExGateBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_ExGateBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_ExGateBase : public EntityCall
{
public:

	EntityCellEntityCall_ExGateBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_ExGateBase();
};

}