/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/ExFlob.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_ExFlobBase : public EntityCall
{
public:

	EntityBaseEntityCall_ExFlobBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_ExFlobBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_ExFlobBase : public EntityCall
{
public:

	EntityCellEntityCall_ExFlobBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_ExFlobBase();
};

}