/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/ExSkill.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_ExSkillBase : public EntityCall
{
public:

	EntityBaseEntityCall_ExSkillBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_ExSkillBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_ExSkillBase : public EntityCall
{
public:

	EntityCellEntityCall_ExSkillBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_ExSkillBase();
};

}