/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/ExRole.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_ExRoleBase : public EntityCall
{
public:

	EntityBaseEntityCall_ExRoleBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_ExRoleBase();
	void LeaveRoom();
	void PassGood(uint8 arg1, uint8 arg2, uint8 arg3, uint8 arg4);
	void ReduceGood(uint8 arg1, uint8 arg2);
	void ReqBagList();
	void ReqTeleportRoom(uint64 arg1);
	void SendChatInfo(const FString& arg1);
};

class KBENGINEPLUGINS_API EntityCellEntityCall_ExRoleBase : public EntityCall
{
public:

	EntityCellEntityCall_ExRoleBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_ExRoleBase();
	void AnimUpdate(const ANIM_INFO& arg1);
	void Attack(const SKILL_INFO& arg1);
	void Relive();
};

}