/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class ExFlob : public ExFlobBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallExFlobBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/ExFlob.def
	// Please inherit and implement "class ExFlob : public ExFlobBase"
class KBENGINEPLUGINS_API ExFlobBase : public Entity
{
public:
	EntityBaseEntityCall_ExFlobBase* pBaseEntityCall;
	EntityCellEntityCall_ExFlobBase* pCellEntityCall;

	uint8 GoodId;
	virtual void onGoodIdChanged(uint8 oldValue) {}


	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	ExFlobBase();
	virtual ~ExFlobBase();

	void attachComponents() override;
	void detachComponents() override;

};

}