/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class ExGate : public ExGateBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallExGateBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/ExGate.def
	// Please inherit and implement "class ExGate : public ExGateBase"
class KBENGINEPLUGINS_API ExGateBase : public Entity
{
public:
	EntityBaseEntityCall_ExGateBase* pBaseEntityCall;
	EntityCellEntityCall_ExGateBase* pCellEntityCall;

	uint64 RoomId;
	virtual void onRoomIdChanged(uint64 oldValue) {}
	FString RoomName;
	virtual void onRoomNameChanged(const FString& oldValue) {}


	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	ExGateBase();
	virtual ~ExGateBase();

	void attachComponents() override;
	void detachComponents() override;

};

}