/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class ExMonster : public ExMonsterBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallExMonsterBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/ExMonster.def
	// Please inherit and implement "class ExMonster : public ExMonsterBase"
class KBENGINEPLUGINS_API ExMonsterBase : public Entity
{
public:
	EntityBaseEntityCall_ExMonsterBase* pBaseEntityCall;
	EntityCellEntityCall_ExMonsterBase* pCellEntityCall;

	int32 BaseHP;
	virtual void onBaseHPChanged(int32 oldValue) {}
	int32 Defense;
	virtual void onDefenseChanged(int32 oldValue) {}
	int32 HP;
	virtual void onHPChanged(int32 oldValue) {}
	FString Name;
	virtual void onNameChanged(const FString& oldValue) {}
	float PowerRatio;
	virtual void onPowerRatioChanged(float oldValue) {}
	uint8 RoleType;
	virtual void onRoleTypeChanged(uint8 oldValue) {}
	float SpeedRatio;
	virtual void onSpeedRatioChanged(float oldValue) {}

	virtual void OnAnimUpdate(const ANIM_INFO& arg1) = 0; 
	virtual void OnAttack() = 0; 

	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	ExMonsterBase();
	virtual ~ExMonsterBase();

	void attachComponents() override;
	void detachComponents() override;

};

}