/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class ExRoomMgr : public ExRoomMgrBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallExRoomMgrBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/ExRoomMgr.def
	// Please inherit and implement "class ExRoomMgr : public ExRoomMgrBase"
class KBENGINEPLUGINS_API ExRoomMgrBase : public Entity
{
public:
	EntityBaseEntityCall_ExRoomMgrBase* pBaseEntityCall;
	EntityCellEntityCall_ExRoomMgrBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	ExRoomMgrBase();
	virtual ~ExRoomMgrBase();

	void attachComponents() override;
	void detachComponents() override;

};

}