/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class ExRoom : public ExRoomBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallExRoomBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/ExRoom.def
	// Please inherit and implement "class ExRoom : public ExRoomBase"
class KBENGINEPLUGINS_API ExRoomBase : public Entity
{
public:
	EntityBaseEntityCall_ExRoomBase* pBaseEntityCall;
	EntityCellEntityCall_ExRoomBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	ExRoomBase();
	virtual ~ExRoomBase();

	void attachComponents() override;
	void detachComponents() override;

};

}