/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class ExSkill : public ExSkillBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallExSkillBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/ExSkill.def
	// Please inherit and implement "class ExSkill : public ExSkillBase"
class KBENGINEPLUGINS_API ExSkillBase : public Entity
{
public:
	EntityBaseEntityCall_ExSkillBase* pBaseEntityCall;
	EntityCellEntityCall_ExSkillBase* pCellEntityCall;

	uint8 SkillId;
	virtual void onSkillIdChanged(uint8 oldValue) {}


	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	ExSkillBase();
	virtual ~ExSkillBase();

	void attachComponents() override;
	void detachComponents() override;

};

}