// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

#include "entity.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

//begin custom modify
#if defined(_MSC_VER)
#pragma warning(disable:4125)
#endif // _MSC_VER
//end custom modify
namespace EntityMsg {
class Struct_PropertyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Struct_Property>
      _instance;
} _Struct_Property_default_instance_;
class Struct_Entity_PropertiesDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Struct_Entity_Properties>
      _instance;
} _Struct_Entity_Properties_default_instance_;
class Notify_Self_Prop_Change_23000DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Notify_Self_Prop_Change_23000>
      _instance;
} _Notify_Self_Prop_Change_23000_default_instance_;
class Brocast_Other_Prop_Change_23001DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Brocast_Other_Prop_Change_23001>
      _instance;
} _Brocast_Other_Prop_Change_23001_default_instance_;
class Brocast_All_Eitities_Prop_23002DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Brocast_All_Eitities_Prop_23002>
      _instance;
} _Brocast_All_Eitities_Prop_23002_default_instance_;
}  // namespace EntityMsg
namespace protobuf_entity_2eproto {
void InitDefaultsStruct_PropertyImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::EntityMsg::_Struct_Property_default_instance_;
    new (ptr) ::EntityMsg::Struct_Property();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::EntityMsg::Struct_Property::InitAsDefaultInstance();
}

void InitDefaultsStruct_Property() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsStruct_PropertyImpl);
}

void InitDefaultsStruct_Entity_PropertiesImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_entity_2eproto::InitDefaultsStruct_Property();
  {
    void* ptr = &::EntityMsg::_Struct_Entity_Properties_default_instance_;
    new (ptr) ::EntityMsg::Struct_Entity_Properties();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::EntityMsg::Struct_Entity_Properties::InitAsDefaultInstance();
}

void InitDefaultsStruct_Entity_Properties() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsStruct_Entity_PropertiesImpl);
}

void InitDefaultsNotify_Self_Prop_Change_23000Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_entity_2eproto::InitDefaultsStruct_Property();
  {
    void* ptr = &::EntityMsg::_Notify_Self_Prop_Change_23000_default_instance_;
    new (ptr) ::EntityMsg::Notify_Self_Prop_Change_23000();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::EntityMsg::Notify_Self_Prop_Change_23000::InitAsDefaultInstance();
}

void InitDefaultsNotify_Self_Prop_Change_23000() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsNotify_Self_Prop_Change_23000Impl);
}

void InitDefaultsBrocast_Other_Prop_Change_23001Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_entity_2eproto::InitDefaultsStruct_Property();
  {
    void* ptr = &::EntityMsg::_Brocast_Other_Prop_Change_23001_default_instance_;
    new (ptr) ::EntityMsg::Brocast_Other_Prop_Change_23001();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::EntityMsg::Brocast_Other_Prop_Change_23001::InitAsDefaultInstance();
}

void InitDefaultsBrocast_Other_Prop_Change_23001() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsBrocast_Other_Prop_Change_23001Impl);
}

void InitDefaultsBrocast_All_Eitities_Prop_23002Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_entity_2eproto::InitDefaultsStruct_Entity_Properties();
  {
    void* ptr = &::EntityMsg::_Brocast_All_Eitities_Prop_23002_default_instance_;
    new (ptr) ::EntityMsg::Brocast_All_Eitities_Prop_23002();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::EntityMsg::Brocast_All_Eitities_Prop_23002::InitAsDefaultInstance();
}

void InitDefaultsBrocast_All_Eitities_Prop_23002() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsBrocast_All_Eitities_Prop_23002Impl);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Struct_Property, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Struct_Property, propid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Struct_Property, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Struct_Entity_Properties, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Struct_Entity_Properties, entityuuid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Struct_Entity_Properties, properties_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Notify_Self_Prop_Change_23000, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Notify_Self_Prop_Change_23000, playerid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Notify_Self_Prop_Change_23000, changedprops_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Notify_Self_Prop_Change_23000, rpcid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Notify_Self_Prop_Change_23000, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Notify_Self_Prop_Change_23000, error_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Brocast_Other_Prop_Change_23001, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Brocast_Other_Prop_Change_23001, entityuuid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Brocast_Other_Prop_Change_23001, changedprops_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Brocast_Other_Prop_Change_23001, rpcid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Brocast_Other_Prop_Change_23001, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Brocast_Other_Prop_Change_23001, error_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Brocast_All_Eitities_Prop_23002, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Brocast_All_Eitities_Prop_23002, entitiesprops_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Brocast_All_Eitities_Prop_23002, rpcid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Brocast_All_Eitities_Prop_23002, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EntityMsg::Brocast_All_Eitities_Prop_23002, error_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::EntityMsg::Struct_Property)},
  { 7, -1, sizeof(::EntityMsg::Struct_Entity_Properties)},
  { 14, -1, sizeof(::EntityMsg::Notify_Self_Prop_Change_23000)},
  { 24, -1, sizeof(::EntityMsg::Brocast_Other_Prop_Change_23001)},
  { 34, -1, sizeof(::EntityMsg::Brocast_All_Eitities_Prop_23002)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::EntityMsg::_Struct_Property_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::EntityMsg::_Struct_Entity_Properties_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::EntityMsg::_Notify_Self_Prop_Change_23000_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::EntityMsg::_Brocast_Other_Prop_Change_23001_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::EntityMsg::_Brocast_All_Eitities_Prop_23002_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "entity.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014entity.proto\022\tEntityMsg\"0\n\017Struct_Prop"
      "erty\022\016\n\006PropID\030\001 \001(\005\022\r\n\005Value\030\002 \001(\005\"^\n\030S"
      "truct_Entity_Properties\022\022\n\nentityUUID\030\001 "
      "\001(\003\022.\n\nproperties\030\002 \003(\0132\032.EntityMsg.Stru"
      "ct_Property\"\222\001\n\035Notify_Self_Prop_Change_"
      "23000\022\020\n\010PlayerID\030\001 \001(\003\0220\n\014changedProps\030"
      "\002 \003(\0132\032.EntityMsg.Struct_Property\022\r\n\005Rpc"
      "Id\030\003 \001(\005\022\017\n\007Message\030\004 \001(\t\022\r\n\005Error\030\005 \001(\005"
      "\"\226\001\n\037Brocast_Other_Prop_Change_23001\022\022\n\n"
      "entityUUID\030\001 \001(\003\0220\n\014changedProps\030\002 \003(\0132\032"
      ".EntityMsg.Struct_Property\022\r\n\005RpcId\030\003 \001("
      "\005\022\017\n\007Message\030\004 \001(\t\022\r\n\005Error\030\005 \001(\005\"\214\001\n\037Br"
      "ocast_All_Eitities_Prop_23002\022:\n\rEntitie"
      "sProps\030\001 \003(\0132#.EntityMsg.Struct_Entity_P"
      "roperties\022\r\n\005RpcId\030\002 \001(\005\022\017\n\007Message\030\003 \001("
      "\t\022\r\n\005Error\030\004 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 624);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "entity.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_entity_2eproto
namespace EntityMsg {

// ===================================================================

void Struct_Property::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Struct_Property::kPropIDFieldNumber;
const int Struct_Property::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Struct_Property::Struct_Property()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_entity_2eproto::InitDefaultsStruct_Property();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:EntityMsg.Struct_Property)
}
Struct_Property::Struct_Property(const Struct_Property& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&propid_, &from.propid_,
    static_cast<size_t>(reinterpret_cast<char*>(&value_) -
    reinterpret_cast<char*>(&propid_)) + sizeof(value_));
  // @@protoc_insertion_point(copy_constructor:EntityMsg.Struct_Property)
}

void Struct_Property::SharedCtor() {
  ::memset(&propid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_) -
      reinterpret_cast<char*>(&propid_)) + sizeof(value_));
  _cached_size_ = 0;
}

Struct_Property::~Struct_Property() {
  // @@protoc_insertion_point(destructor:EntityMsg.Struct_Property)
  SharedDtor();
}

void Struct_Property::SharedDtor() {
}

void Struct_Property::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Struct_Property::descriptor() {
  ::protobuf_entity_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_entity_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Struct_Property& Struct_Property::default_instance() {
  ::protobuf_entity_2eproto::InitDefaultsStruct_Property();
  return *internal_default_instance();
}

Struct_Property* Struct_Property::New(::google::protobuf::Arena* arena) const {
  Struct_Property* n = new Struct_Property;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Struct_Property::Clear() {
// @@protoc_insertion_point(message_clear_start:EntityMsg.Struct_Property)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&propid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_) -
      reinterpret_cast<char*>(&propid_)) + sizeof(value_));
  _internal_metadata_.Clear();
}

bool Struct_Property::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:EntityMsg.Struct_Property)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 PropID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &propid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 Value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:EntityMsg.Struct_Property)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:EntityMsg.Struct_Property)
  return false;
#undef DO_
}

void Struct_Property::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:EntityMsg.Struct_Property)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 PropID = 1;
  if (this->propid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->propid(), output);
  }

  // int32 Value = 2;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:EntityMsg.Struct_Property)
}

::google::protobuf::uint8* Struct_Property::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:EntityMsg.Struct_Property)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 PropID = 1;
  if (this->propid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->propid(), target);
  }

  // int32 Value = 2;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EntityMsg.Struct_Property)
  return target;
}

size_t Struct_Property::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:EntityMsg.Struct_Property)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 PropID = 1;
  if (this->propid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->propid());
  }

  // int32 Value = 2;
  if (this->value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Struct_Property::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:EntityMsg.Struct_Property)
  GOOGLE_DCHECK_NE(&from, this);
  const Struct_Property* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Struct_Property>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:EntityMsg.Struct_Property)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:EntityMsg.Struct_Property)
    MergeFrom(*source);
  }
}

void Struct_Property::MergeFrom(const Struct_Property& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:EntityMsg.Struct_Property)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.propid() != 0) {
    set_propid(from.propid());
  }
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void Struct_Property::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:EntityMsg.Struct_Property)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Struct_Property::CopyFrom(const Struct_Property& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EntityMsg.Struct_Property)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Struct_Property::IsInitialized() const {
  return true;
}

void Struct_Property::Swap(Struct_Property* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Struct_Property::InternalSwap(Struct_Property* other) {
  using std::swap;
  swap(propid_, other->propid_);
  swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Struct_Property::GetMetadata() const {
  protobuf_entity_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_entity_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Struct_Entity_Properties::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Struct_Entity_Properties::kEntityUUIDFieldNumber;
const int Struct_Entity_Properties::kPropertiesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Struct_Entity_Properties::Struct_Entity_Properties()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_entity_2eproto::InitDefaultsStruct_Entity_Properties();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:EntityMsg.Struct_Entity_Properties)
}
Struct_Entity_Properties::Struct_Entity_Properties(const Struct_Entity_Properties& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      properties_(from.properties_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  entityuuid_ = from.entityuuid_;
  // @@protoc_insertion_point(copy_constructor:EntityMsg.Struct_Entity_Properties)
}

void Struct_Entity_Properties::SharedCtor() {
  entityuuid_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

Struct_Entity_Properties::~Struct_Entity_Properties() {
  // @@protoc_insertion_point(destructor:EntityMsg.Struct_Entity_Properties)
  SharedDtor();
}

void Struct_Entity_Properties::SharedDtor() {
}

void Struct_Entity_Properties::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Struct_Entity_Properties::descriptor() {
  ::protobuf_entity_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_entity_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Struct_Entity_Properties& Struct_Entity_Properties::default_instance() {
  ::protobuf_entity_2eproto::InitDefaultsStruct_Entity_Properties();
  return *internal_default_instance();
}

Struct_Entity_Properties* Struct_Entity_Properties::New(::google::protobuf::Arena* arena) const {
  Struct_Entity_Properties* n = new Struct_Entity_Properties;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Struct_Entity_Properties::Clear() {
// @@protoc_insertion_point(message_clear_start:EntityMsg.Struct_Entity_Properties)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  properties_.Clear();
  entityuuid_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool Struct_Entity_Properties::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:EntityMsg.Struct_Entity_Properties)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 entityUUID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &entityuuid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .EntityMsg.Struct_Property properties = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_properties()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:EntityMsg.Struct_Entity_Properties)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:EntityMsg.Struct_Entity_Properties)
  return false;
#undef DO_
}

void Struct_Entity_Properties::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:EntityMsg.Struct_Entity_Properties)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 entityUUID = 1;
  if (this->entityuuid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->entityuuid(), output);
  }

  // repeated .EntityMsg.Struct_Property properties = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->properties_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->properties(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:EntityMsg.Struct_Entity_Properties)
}

::google::protobuf::uint8* Struct_Entity_Properties::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:EntityMsg.Struct_Entity_Properties)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 entityUUID = 1;
  if (this->entityuuid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->entityuuid(), target);
  }

  // repeated .EntityMsg.Struct_Property properties = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->properties_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->properties(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EntityMsg.Struct_Entity_Properties)
  return target;
}

size_t Struct_Entity_Properties::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:EntityMsg.Struct_Entity_Properties)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .EntityMsg.Struct_Property properties = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->properties_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->properties(static_cast<int>(i)));
    }
  }

  // int64 entityUUID = 1;
  if (this->entityuuid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->entityuuid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Struct_Entity_Properties::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:EntityMsg.Struct_Entity_Properties)
  GOOGLE_DCHECK_NE(&from, this);
  const Struct_Entity_Properties* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Struct_Entity_Properties>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:EntityMsg.Struct_Entity_Properties)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:EntityMsg.Struct_Entity_Properties)
    MergeFrom(*source);
  }
}

void Struct_Entity_Properties::MergeFrom(const Struct_Entity_Properties& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:EntityMsg.Struct_Entity_Properties)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  properties_.MergeFrom(from.properties_);
  if (from.entityuuid() != 0) {
    set_entityuuid(from.entityuuid());
  }
}

void Struct_Entity_Properties::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:EntityMsg.Struct_Entity_Properties)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Struct_Entity_Properties::CopyFrom(const Struct_Entity_Properties& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EntityMsg.Struct_Entity_Properties)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Struct_Entity_Properties::IsInitialized() const {
  return true;
}

void Struct_Entity_Properties::Swap(Struct_Entity_Properties* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Struct_Entity_Properties::InternalSwap(Struct_Entity_Properties* other) {
  using std::swap;
  properties_.InternalSwap(&other->properties_);
  swap(entityuuid_, other->entityuuid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Struct_Entity_Properties::GetMetadata() const {
  protobuf_entity_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_entity_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Notify_Self_Prop_Change_23000::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Notify_Self_Prop_Change_23000::kPlayerIDFieldNumber;
const int Notify_Self_Prop_Change_23000::kChangedPropsFieldNumber;
const int Notify_Self_Prop_Change_23000::kRpcIdFieldNumber;
const int Notify_Self_Prop_Change_23000::kMessageFieldNumber;
const int Notify_Self_Prop_Change_23000::kErrorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Notify_Self_Prop_Change_23000::Notify_Self_Prop_Change_23000()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_entity_2eproto::InitDefaultsNotify_Self_Prop_Change_23000();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:EntityMsg.Notify_Self_Prop_Change_23000)
}
Notify_Self_Prop_Change_23000::Notify_Self_Prop_Change_23000(const Notify_Self_Prop_Change_23000& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      changedprops_(from.changedprops_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  ::memcpy(&playerid_, &from.playerid_,
    static_cast<size_t>(reinterpret_cast<char*>(&error_) -
    reinterpret_cast<char*>(&playerid_)) + sizeof(error_));
  // @@protoc_insertion_point(copy_constructor:EntityMsg.Notify_Self_Prop_Change_23000)
}

void Notify_Self_Prop_Change_23000::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&playerid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&playerid_)) + sizeof(error_));
  _cached_size_ = 0;
}

Notify_Self_Prop_Change_23000::~Notify_Self_Prop_Change_23000() {
  // @@protoc_insertion_point(destructor:EntityMsg.Notify_Self_Prop_Change_23000)
  SharedDtor();
}

void Notify_Self_Prop_Change_23000::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Notify_Self_Prop_Change_23000::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Notify_Self_Prop_Change_23000::descriptor() {
  ::protobuf_entity_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_entity_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Notify_Self_Prop_Change_23000& Notify_Self_Prop_Change_23000::default_instance() {
  ::protobuf_entity_2eproto::InitDefaultsNotify_Self_Prop_Change_23000();
  return *internal_default_instance();
}

Notify_Self_Prop_Change_23000* Notify_Self_Prop_Change_23000::New(::google::protobuf::Arena* arena) const {
  Notify_Self_Prop_Change_23000* n = new Notify_Self_Prop_Change_23000;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Notify_Self_Prop_Change_23000::Clear() {
// @@protoc_insertion_point(message_clear_start:EntityMsg.Notify_Self_Prop_Change_23000)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  changedprops_.Clear();
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&playerid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&playerid_)) + sizeof(error_));
  _internal_metadata_.Clear();
}

bool Notify_Self_Prop_Change_23000::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:EntityMsg.Notify_Self_Prop_Change_23000)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 PlayerID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &playerid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .EntityMsg.Struct_Property changedProps = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_changedprops()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 RpcId = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rpcid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Message = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "EntityMsg.Notify_Self_Prop_Change_23000.Message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 Error = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:EntityMsg.Notify_Self_Prop_Change_23000)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:EntityMsg.Notify_Self_Prop_Change_23000)
  return false;
#undef DO_
}

void Notify_Self_Prop_Change_23000::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:EntityMsg.Notify_Self_Prop_Change_23000)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 PlayerID = 1;
  if (this->playerid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->playerid(), output);
  }

  // repeated .EntityMsg.Struct_Property changedProps = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->changedprops_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->changedprops(static_cast<int>(i)), output);
  }

  // int32 RpcId = 3;
  if (this->rpcid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->rpcid(), output);
  }

  // string Message = 4;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "EntityMsg.Notify_Self_Prop_Change_23000.Message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->message(), output);
  }

  // int32 Error = 5;
  if (this->error() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->error(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:EntityMsg.Notify_Self_Prop_Change_23000)
}

::google::protobuf::uint8* Notify_Self_Prop_Change_23000::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:EntityMsg.Notify_Self_Prop_Change_23000)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 PlayerID = 1;
  if (this->playerid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->playerid(), target);
  }

  // repeated .EntityMsg.Struct_Property changedProps = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->changedprops_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->changedprops(static_cast<int>(i)), deterministic, target);
  }

  // int32 RpcId = 3;
  if (this->rpcid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->rpcid(), target);
  }

  // string Message = 4;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "EntityMsg.Notify_Self_Prop_Change_23000.Message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->message(), target);
  }

  // int32 Error = 5;
  if (this->error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->error(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EntityMsg.Notify_Self_Prop_Change_23000)
  return target;
}

size_t Notify_Self_Prop_Change_23000::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:EntityMsg.Notify_Self_Prop_Change_23000)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .EntityMsg.Struct_Property changedProps = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->changedprops_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->changedprops(static_cast<int>(i)));
    }
  }

  // string Message = 4;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // int64 PlayerID = 1;
  if (this->playerid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->playerid());
  }

  // int32 RpcId = 3;
  if (this->rpcid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rpcid());
  }

  // int32 Error = 5;
  if (this->error() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Notify_Self_Prop_Change_23000::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:EntityMsg.Notify_Self_Prop_Change_23000)
  GOOGLE_DCHECK_NE(&from, this);
  const Notify_Self_Prop_Change_23000* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Notify_Self_Prop_Change_23000>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:EntityMsg.Notify_Self_Prop_Change_23000)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:EntityMsg.Notify_Self_Prop_Change_23000)
    MergeFrom(*source);
  }
}

void Notify_Self_Prop_Change_23000::MergeFrom(const Notify_Self_Prop_Change_23000& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:EntityMsg.Notify_Self_Prop_Change_23000)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  changedprops_.MergeFrom(from.changedprops_);
  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.playerid() != 0) {
    set_playerid(from.playerid());
  }
  if (from.rpcid() != 0) {
    set_rpcid(from.rpcid());
  }
  if (from.error() != 0) {
    set_error(from.error());
  }
}

void Notify_Self_Prop_Change_23000::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:EntityMsg.Notify_Self_Prop_Change_23000)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Notify_Self_Prop_Change_23000::CopyFrom(const Notify_Self_Prop_Change_23000& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EntityMsg.Notify_Self_Prop_Change_23000)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Notify_Self_Prop_Change_23000::IsInitialized() const {
  return true;
}

void Notify_Self_Prop_Change_23000::Swap(Notify_Self_Prop_Change_23000* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Notify_Self_Prop_Change_23000::InternalSwap(Notify_Self_Prop_Change_23000* other) {
  using std::swap;
  changedprops_.InternalSwap(&other->changedprops_);
  message_.Swap(&other->message_);
  swap(playerid_, other->playerid_);
  swap(rpcid_, other->rpcid_);
  swap(error_, other->error_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Notify_Self_Prop_Change_23000::GetMetadata() const {
  protobuf_entity_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_entity_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Brocast_Other_Prop_Change_23001::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Brocast_Other_Prop_Change_23001::kEntityUUIDFieldNumber;
const int Brocast_Other_Prop_Change_23001::kChangedPropsFieldNumber;
const int Brocast_Other_Prop_Change_23001::kRpcIdFieldNumber;
const int Brocast_Other_Prop_Change_23001::kMessageFieldNumber;
const int Brocast_Other_Prop_Change_23001::kErrorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Brocast_Other_Prop_Change_23001::Brocast_Other_Prop_Change_23001()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_entity_2eproto::InitDefaultsBrocast_Other_Prop_Change_23001();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:EntityMsg.Brocast_Other_Prop_Change_23001)
}
Brocast_Other_Prop_Change_23001::Brocast_Other_Prop_Change_23001(const Brocast_Other_Prop_Change_23001& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      changedprops_(from.changedprops_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  ::memcpy(&entityuuid_, &from.entityuuid_,
    static_cast<size_t>(reinterpret_cast<char*>(&error_) -
    reinterpret_cast<char*>(&entityuuid_)) + sizeof(error_));
  // @@protoc_insertion_point(copy_constructor:EntityMsg.Brocast_Other_Prop_Change_23001)
}

void Brocast_Other_Prop_Change_23001::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&entityuuid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&entityuuid_)) + sizeof(error_));
  _cached_size_ = 0;
}

Brocast_Other_Prop_Change_23001::~Brocast_Other_Prop_Change_23001() {
  // @@protoc_insertion_point(destructor:EntityMsg.Brocast_Other_Prop_Change_23001)
  SharedDtor();
}

void Brocast_Other_Prop_Change_23001::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Brocast_Other_Prop_Change_23001::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Brocast_Other_Prop_Change_23001::descriptor() {
  ::protobuf_entity_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_entity_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Brocast_Other_Prop_Change_23001& Brocast_Other_Prop_Change_23001::default_instance() {
  ::protobuf_entity_2eproto::InitDefaultsBrocast_Other_Prop_Change_23001();
  return *internal_default_instance();
}

Brocast_Other_Prop_Change_23001* Brocast_Other_Prop_Change_23001::New(::google::protobuf::Arena* arena) const {
  Brocast_Other_Prop_Change_23001* n = new Brocast_Other_Prop_Change_23001;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Brocast_Other_Prop_Change_23001::Clear() {
// @@protoc_insertion_point(message_clear_start:EntityMsg.Brocast_Other_Prop_Change_23001)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  changedprops_.Clear();
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&entityuuid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&entityuuid_)) + sizeof(error_));
  _internal_metadata_.Clear();
}

bool Brocast_Other_Prop_Change_23001::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:EntityMsg.Brocast_Other_Prop_Change_23001)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 entityUUID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &entityuuid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .EntityMsg.Struct_Property changedProps = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_changedprops()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 RpcId = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rpcid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Message = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "EntityMsg.Brocast_Other_Prop_Change_23001.Message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 Error = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:EntityMsg.Brocast_Other_Prop_Change_23001)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:EntityMsg.Brocast_Other_Prop_Change_23001)
  return false;
#undef DO_
}

void Brocast_Other_Prop_Change_23001::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:EntityMsg.Brocast_Other_Prop_Change_23001)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 entityUUID = 1;
  if (this->entityuuid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->entityuuid(), output);
  }

  // repeated .EntityMsg.Struct_Property changedProps = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->changedprops_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->changedprops(static_cast<int>(i)), output);
  }

  // int32 RpcId = 3;
  if (this->rpcid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->rpcid(), output);
  }

  // string Message = 4;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "EntityMsg.Brocast_Other_Prop_Change_23001.Message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->message(), output);
  }

  // int32 Error = 5;
  if (this->error() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->error(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:EntityMsg.Brocast_Other_Prop_Change_23001)
}

::google::protobuf::uint8* Brocast_Other_Prop_Change_23001::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:EntityMsg.Brocast_Other_Prop_Change_23001)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 entityUUID = 1;
  if (this->entityuuid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->entityuuid(), target);
  }

  // repeated .EntityMsg.Struct_Property changedProps = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->changedprops_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->changedprops(static_cast<int>(i)), deterministic, target);
  }

  // int32 RpcId = 3;
  if (this->rpcid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->rpcid(), target);
  }

  // string Message = 4;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "EntityMsg.Brocast_Other_Prop_Change_23001.Message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->message(), target);
  }

  // int32 Error = 5;
  if (this->error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->error(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EntityMsg.Brocast_Other_Prop_Change_23001)
  return target;
}

size_t Brocast_Other_Prop_Change_23001::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:EntityMsg.Brocast_Other_Prop_Change_23001)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .EntityMsg.Struct_Property changedProps = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->changedprops_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->changedprops(static_cast<int>(i)));
    }
  }

  // string Message = 4;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // int64 entityUUID = 1;
  if (this->entityuuid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->entityuuid());
  }

  // int32 RpcId = 3;
  if (this->rpcid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rpcid());
  }

  // int32 Error = 5;
  if (this->error() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Brocast_Other_Prop_Change_23001::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:EntityMsg.Brocast_Other_Prop_Change_23001)
  GOOGLE_DCHECK_NE(&from, this);
  const Brocast_Other_Prop_Change_23001* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Brocast_Other_Prop_Change_23001>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:EntityMsg.Brocast_Other_Prop_Change_23001)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:EntityMsg.Brocast_Other_Prop_Change_23001)
    MergeFrom(*source);
  }
}

void Brocast_Other_Prop_Change_23001::MergeFrom(const Brocast_Other_Prop_Change_23001& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:EntityMsg.Brocast_Other_Prop_Change_23001)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  changedprops_.MergeFrom(from.changedprops_);
  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.entityuuid() != 0) {
    set_entityuuid(from.entityuuid());
  }
  if (from.rpcid() != 0) {
    set_rpcid(from.rpcid());
  }
  if (from.error() != 0) {
    set_error(from.error());
  }
}

void Brocast_Other_Prop_Change_23001::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:EntityMsg.Brocast_Other_Prop_Change_23001)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Brocast_Other_Prop_Change_23001::CopyFrom(const Brocast_Other_Prop_Change_23001& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EntityMsg.Brocast_Other_Prop_Change_23001)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Brocast_Other_Prop_Change_23001::IsInitialized() const {
  return true;
}

void Brocast_Other_Prop_Change_23001::Swap(Brocast_Other_Prop_Change_23001* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Brocast_Other_Prop_Change_23001::InternalSwap(Brocast_Other_Prop_Change_23001* other) {
  using std::swap;
  changedprops_.InternalSwap(&other->changedprops_);
  message_.Swap(&other->message_);
  swap(entityuuid_, other->entityuuid_);
  swap(rpcid_, other->rpcid_);
  swap(error_, other->error_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Brocast_Other_Prop_Change_23001::GetMetadata() const {
  protobuf_entity_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_entity_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Brocast_All_Eitities_Prop_23002::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Brocast_All_Eitities_Prop_23002::kEntitiesPropsFieldNumber;
const int Brocast_All_Eitities_Prop_23002::kRpcIdFieldNumber;
const int Brocast_All_Eitities_Prop_23002::kMessageFieldNumber;
const int Brocast_All_Eitities_Prop_23002::kErrorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Brocast_All_Eitities_Prop_23002::Brocast_All_Eitities_Prop_23002()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_entity_2eproto::InitDefaultsBrocast_All_Eitities_Prop_23002();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:EntityMsg.Brocast_All_Eitities_Prop_23002)
}
Brocast_All_Eitities_Prop_23002::Brocast_All_Eitities_Prop_23002(const Brocast_All_Eitities_Prop_23002& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      entitiesprops_(from.entitiesprops_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  ::memcpy(&rpcid_, &from.rpcid_,
    static_cast<size_t>(reinterpret_cast<char*>(&error_) -
    reinterpret_cast<char*>(&rpcid_)) + sizeof(error_));
  // @@protoc_insertion_point(copy_constructor:EntityMsg.Brocast_All_Eitities_Prop_23002)
}

void Brocast_All_Eitities_Prop_23002::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&rpcid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&rpcid_)) + sizeof(error_));
  _cached_size_ = 0;
}

Brocast_All_Eitities_Prop_23002::~Brocast_All_Eitities_Prop_23002() {
  // @@protoc_insertion_point(destructor:EntityMsg.Brocast_All_Eitities_Prop_23002)
  SharedDtor();
}

void Brocast_All_Eitities_Prop_23002::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Brocast_All_Eitities_Prop_23002::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Brocast_All_Eitities_Prop_23002::descriptor() {
  ::protobuf_entity_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_entity_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Brocast_All_Eitities_Prop_23002& Brocast_All_Eitities_Prop_23002::default_instance() {
  ::protobuf_entity_2eproto::InitDefaultsBrocast_All_Eitities_Prop_23002();
  return *internal_default_instance();
}

Brocast_All_Eitities_Prop_23002* Brocast_All_Eitities_Prop_23002::New(::google::protobuf::Arena* arena) const {
  Brocast_All_Eitities_Prop_23002* n = new Brocast_All_Eitities_Prop_23002;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Brocast_All_Eitities_Prop_23002::Clear() {
// @@protoc_insertion_point(message_clear_start:EntityMsg.Brocast_All_Eitities_Prop_23002)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  entitiesprops_.Clear();
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&rpcid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&rpcid_)) + sizeof(error_));
  _internal_metadata_.Clear();
}

bool Brocast_All_Eitities_Prop_23002::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:EntityMsg.Brocast_All_Eitities_Prop_23002)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .EntityMsg.Struct_Entity_Properties EntitiesProps = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_entitiesprops()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 RpcId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rpcid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Message = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "EntityMsg.Brocast_All_Eitities_Prop_23002.Message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 Error = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:EntityMsg.Brocast_All_Eitities_Prop_23002)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:EntityMsg.Brocast_All_Eitities_Prop_23002)
  return false;
#undef DO_
}

void Brocast_All_Eitities_Prop_23002::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:EntityMsg.Brocast_All_Eitities_Prop_23002)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .EntityMsg.Struct_Entity_Properties EntitiesProps = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->entitiesprops_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->entitiesprops(static_cast<int>(i)), output);
  }

  // int32 RpcId = 2;
  if (this->rpcid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->rpcid(), output);
  }

  // string Message = 3;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "EntityMsg.Brocast_All_Eitities_Prop_23002.Message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->message(), output);
  }

  // int32 Error = 4;
  if (this->error() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->error(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:EntityMsg.Brocast_All_Eitities_Prop_23002)
}

::google::protobuf::uint8* Brocast_All_Eitities_Prop_23002::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:EntityMsg.Brocast_All_Eitities_Prop_23002)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .EntityMsg.Struct_Entity_Properties EntitiesProps = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->entitiesprops_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->entitiesprops(static_cast<int>(i)), deterministic, target);
  }

  // int32 RpcId = 2;
  if (this->rpcid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->rpcid(), target);
  }

  // string Message = 3;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "EntityMsg.Brocast_All_Eitities_Prop_23002.Message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->message(), target);
  }

  // int32 Error = 4;
  if (this->error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->error(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EntityMsg.Brocast_All_Eitities_Prop_23002)
  return target;
}

size_t Brocast_All_Eitities_Prop_23002::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:EntityMsg.Brocast_All_Eitities_Prop_23002)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .EntityMsg.Struct_Entity_Properties EntitiesProps = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->entitiesprops_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->entitiesprops(static_cast<int>(i)));
    }
  }

  // string Message = 3;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // int32 RpcId = 2;
  if (this->rpcid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rpcid());
  }

  // int32 Error = 4;
  if (this->error() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Brocast_All_Eitities_Prop_23002::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:EntityMsg.Brocast_All_Eitities_Prop_23002)
  GOOGLE_DCHECK_NE(&from, this);
  const Brocast_All_Eitities_Prop_23002* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Brocast_All_Eitities_Prop_23002>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:EntityMsg.Brocast_All_Eitities_Prop_23002)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:EntityMsg.Brocast_All_Eitities_Prop_23002)
    MergeFrom(*source);
  }
}

void Brocast_All_Eitities_Prop_23002::MergeFrom(const Brocast_All_Eitities_Prop_23002& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:EntityMsg.Brocast_All_Eitities_Prop_23002)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  entitiesprops_.MergeFrom(from.entitiesprops_);
  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.rpcid() != 0) {
    set_rpcid(from.rpcid());
  }
  if (from.error() != 0) {
    set_error(from.error());
  }
}

void Brocast_All_Eitities_Prop_23002::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:EntityMsg.Brocast_All_Eitities_Prop_23002)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Brocast_All_Eitities_Prop_23002::CopyFrom(const Brocast_All_Eitities_Prop_23002& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EntityMsg.Brocast_All_Eitities_Prop_23002)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Brocast_All_Eitities_Prop_23002::IsInitialized() const {
  return true;
}

void Brocast_All_Eitities_Prop_23002::Swap(Brocast_All_Eitities_Prop_23002* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Brocast_All_Eitities_Prop_23002::InternalSwap(Brocast_All_Eitities_Prop_23002* other) {
  using std::swap;
  entitiesprops_.InternalSwap(&other->entitiesprops_);
  message_.Swap(&other->message_);
  swap(rpcid_, other->rpcid_);
  swap(error_, other->error_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Brocast_All_Eitities_Prop_23002::GetMetadata() const {
  protobuf_entity_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_entity_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace EntityMsg

// @@protoc_insertion_point(global_scope)
