// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

#ifndef PROTOBUF_entity_2eproto__INCLUDED
#define PROTOBUF_entity_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_entity_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsStruct_PropertyImpl();
void InitDefaultsStruct_Property();
void InitDefaultsStruct_Entity_PropertiesImpl();
void InitDefaultsStruct_Entity_Properties();
void InitDefaultsNotify_Self_Prop_Change_23000Impl();
void InitDefaultsNotify_Self_Prop_Change_23000();
void InitDefaultsBrocast_Other_Prop_Change_23001Impl();
void InitDefaultsBrocast_Other_Prop_Change_23001();
void InitDefaultsBrocast_All_Eitities_Prop_23002Impl();
void InitDefaultsBrocast_All_Eitities_Prop_23002();
inline void InitDefaults() {
  InitDefaultsStruct_Property();
  InitDefaultsStruct_Entity_Properties();
  InitDefaultsNotify_Self_Prop_Change_23000();
  InitDefaultsBrocast_Other_Prop_Change_23001();
  InitDefaultsBrocast_All_Eitities_Prop_23002();
}
}  // namespace protobuf_entity_2eproto
namespace EntityMsg {
class Brocast_All_Eitities_Prop_23002;
class Brocast_All_Eitities_Prop_23002DefaultTypeInternal;
extern Brocast_All_Eitities_Prop_23002DefaultTypeInternal _Brocast_All_Eitities_Prop_23002_default_instance_;
class Brocast_Other_Prop_Change_23001;
class Brocast_Other_Prop_Change_23001DefaultTypeInternal;
extern Brocast_Other_Prop_Change_23001DefaultTypeInternal _Brocast_Other_Prop_Change_23001_default_instance_;
class Notify_Self_Prop_Change_23000;
class Notify_Self_Prop_Change_23000DefaultTypeInternal;
extern Notify_Self_Prop_Change_23000DefaultTypeInternal _Notify_Self_Prop_Change_23000_default_instance_;
class Struct_Entity_Properties;
class Struct_Entity_PropertiesDefaultTypeInternal;
extern Struct_Entity_PropertiesDefaultTypeInternal _Struct_Entity_Properties_default_instance_;
class Struct_Property;
class Struct_PropertyDefaultTypeInternal;
extern Struct_PropertyDefaultTypeInternal _Struct_Property_default_instance_;
}  // namespace EntityMsg
namespace EntityMsg {

// ===================================================================

class Struct_Property : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:EntityMsg.Struct_Property) */ {
 public:
  Struct_Property();
  virtual ~Struct_Property();

  Struct_Property(const Struct_Property& from);

  inline Struct_Property& operator=(const Struct_Property& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Struct_Property(Struct_Property&& from) noexcept
    : Struct_Property() {
    *this = ::std::move(from);
  }

  inline Struct_Property& operator=(Struct_Property&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Struct_Property& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Struct_Property* internal_default_instance() {
    return reinterpret_cast<const Struct_Property*>(
               &_Struct_Property_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Struct_Property* other);
  friend void swap(Struct_Property& a, Struct_Property& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Struct_Property* New() const PROTOBUF_FINAL { return New(NULL); }

  Struct_Property* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Struct_Property& from);
  void MergeFrom(const Struct_Property& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Struct_Property* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 PropID = 1;
  void clear_propid();
  static const int kPropIDFieldNumber = 1;
  ::google::protobuf::int32 propid() const;
  void set_propid(::google::protobuf::int32 value);

  // int32 Value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  ::google::protobuf::int32 value() const;
  void set_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:EntityMsg.Struct_Property)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 propid_;
  ::google::protobuf::int32 value_;
  mutable int _cached_size_;
  friend struct ::protobuf_entity_2eproto::TableStruct;
  friend void ::protobuf_entity_2eproto::InitDefaultsStruct_PropertyImpl();
};
// -------------------------------------------------------------------

class Struct_Entity_Properties : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:EntityMsg.Struct_Entity_Properties) */ {
 public:
  Struct_Entity_Properties();
  virtual ~Struct_Entity_Properties();

  Struct_Entity_Properties(const Struct_Entity_Properties& from);

  inline Struct_Entity_Properties& operator=(const Struct_Entity_Properties& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Struct_Entity_Properties(Struct_Entity_Properties&& from) noexcept
    : Struct_Entity_Properties() {
    *this = ::std::move(from);
  }

  inline Struct_Entity_Properties& operator=(Struct_Entity_Properties&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Struct_Entity_Properties& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Struct_Entity_Properties* internal_default_instance() {
    return reinterpret_cast<const Struct_Entity_Properties*>(
               &_Struct_Entity_Properties_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Struct_Entity_Properties* other);
  friend void swap(Struct_Entity_Properties& a, Struct_Entity_Properties& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Struct_Entity_Properties* New() const PROTOBUF_FINAL { return New(NULL); }

  Struct_Entity_Properties* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Struct_Entity_Properties& from);
  void MergeFrom(const Struct_Entity_Properties& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Struct_Entity_Properties* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .EntityMsg.Struct_Property properties = 2;
  int properties_size() const;
  void clear_properties();
  static const int kPropertiesFieldNumber = 2;
  const ::EntityMsg::Struct_Property& properties(int index) const;
  ::EntityMsg::Struct_Property* mutable_properties(int index);
  ::EntityMsg::Struct_Property* add_properties();
  ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property >*
      mutable_properties();
  const ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property >&
      properties() const;

  // int64 entityUUID = 1;
  void clear_entityuuid();
  static const int kEntityUUIDFieldNumber = 1;
  ::google::protobuf::int64 entityuuid() const;
  void set_entityuuid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:EntityMsg.Struct_Entity_Properties)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property > properties_;
  ::google::protobuf::int64 entityuuid_;
  mutable int _cached_size_;
  friend struct ::protobuf_entity_2eproto::TableStruct;
  friend void ::protobuf_entity_2eproto::InitDefaultsStruct_Entity_PropertiesImpl();
};
// -------------------------------------------------------------------

class Notify_Self_Prop_Change_23000 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:EntityMsg.Notify_Self_Prop_Change_23000) */ {
 public:
  Notify_Self_Prop_Change_23000();
  virtual ~Notify_Self_Prop_Change_23000();

  Notify_Self_Prop_Change_23000(const Notify_Self_Prop_Change_23000& from);

  inline Notify_Self_Prop_Change_23000& operator=(const Notify_Self_Prop_Change_23000& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Notify_Self_Prop_Change_23000(Notify_Self_Prop_Change_23000&& from) noexcept
    : Notify_Self_Prop_Change_23000() {
    *this = ::std::move(from);
  }

  inline Notify_Self_Prop_Change_23000& operator=(Notify_Self_Prop_Change_23000&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Notify_Self_Prop_Change_23000& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Notify_Self_Prop_Change_23000* internal_default_instance() {
    return reinterpret_cast<const Notify_Self_Prop_Change_23000*>(
               &_Notify_Self_Prop_Change_23000_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Notify_Self_Prop_Change_23000* other);
  friend void swap(Notify_Self_Prop_Change_23000& a, Notify_Self_Prop_Change_23000& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Notify_Self_Prop_Change_23000* New() const PROTOBUF_FINAL { return New(NULL); }

  Notify_Self_Prop_Change_23000* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Notify_Self_Prop_Change_23000& from);
  void MergeFrom(const Notify_Self_Prop_Change_23000& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Notify_Self_Prop_Change_23000* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .EntityMsg.Struct_Property changedProps = 2;
  int changedprops_size() const;
  void clear_changedprops();
  static const int kChangedPropsFieldNumber = 2;
  const ::EntityMsg::Struct_Property& changedprops(int index) const;
  ::EntityMsg::Struct_Property* mutable_changedprops(int index);
  ::EntityMsg::Struct_Property* add_changedprops();
  ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property >*
      mutable_changedprops();
  const ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property >&
      changedprops() const;

  // string Message = 4;
  void clear_message();
  static const int kMessageFieldNumber = 4;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int64 PlayerID = 1;
  void clear_playerid();
  static const int kPlayerIDFieldNumber = 1;
  ::google::protobuf::int64 playerid() const;
  void set_playerid(::google::protobuf::int64 value);

  // int32 RpcId = 3;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 3;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // int32 Error = 5;
  void clear_error();
  static const int kErrorFieldNumber = 5;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:EntityMsg.Notify_Self_Prop_Change_23000)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property > changedprops_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int64 playerid_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  mutable int _cached_size_;
  friend struct ::protobuf_entity_2eproto::TableStruct;
  friend void ::protobuf_entity_2eproto::InitDefaultsNotify_Self_Prop_Change_23000Impl();
};
// -------------------------------------------------------------------

class Brocast_Other_Prop_Change_23001 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:EntityMsg.Brocast_Other_Prop_Change_23001) */ {
 public:
  Brocast_Other_Prop_Change_23001();
  virtual ~Brocast_Other_Prop_Change_23001();

  Brocast_Other_Prop_Change_23001(const Brocast_Other_Prop_Change_23001& from);

  inline Brocast_Other_Prop_Change_23001& operator=(const Brocast_Other_Prop_Change_23001& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Brocast_Other_Prop_Change_23001(Brocast_Other_Prop_Change_23001&& from) noexcept
    : Brocast_Other_Prop_Change_23001() {
    *this = ::std::move(from);
  }

  inline Brocast_Other_Prop_Change_23001& operator=(Brocast_Other_Prop_Change_23001&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Brocast_Other_Prop_Change_23001& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Brocast_Other_Prop_Change_23001* internal_default_instance() {
    return reinterpret_cast<const Brocast_Other_Prop_Change_23001*>(
               &_Brocast_Other_Prop_Change_23001_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Brocast_Other_Prop_Change_23001* other);
  friend void swap(Brocast_Other_Prop_Change_23001& a, Brocast_Other_Prop_Change_23001& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Brocast_Other_Prop_Change_23001* New() const PROTOBUF_FINAL { return New(NULL); }

  Brocast_Other_Prop_Change_23001* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Brocast_Other_Prop_Change_23001& from);
  void MergeFrom(const Brocast_Other_Prop_Change_23001& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Brocast_Other_Prop_Change_23001* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .EntityMsg.Struct_Property changedProps = 2;
  int changedprops_size() const;
  void clear_changedprops();
  static const int kChangedPropsFieldNumber = 2;
  const ::EntityMsg::Struct_Property& changedprops(int index) const;
  ::EntityMsg::Struct_Property* mutable_changedprops(int index);
  ::EntityMsg::Struct_Property* add_changedprops();
  ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property >*
      mutable_changedprops();
  const ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property >&
      changedprops() const;

  // string Message = 4;
  void clear_message();
  static const int kMessageFieldNumber = 4;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int64 entityUUID = 1;
  void clear_entityuuid();
  static const int kEntityUUIDFieldNumber = 1;
  ::google::protobuf::int64 entityuuid() const;
  void set_entityuuid(::google::protobuf::int64 value);

  // int32 RpcId = 3;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 3;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // int32 Error = 5;
  void clear_error();
  static const int kErrorFieldNumber = 5;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:EntityMsg.Brocast_Other_Prop_Change_23001)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property > changedprops_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int64 entityuuid_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  mutable int _cached_size_;
  friend struct ::protobuf_entity_2eproto::TableStruct;
  friend void ::protobuf_entity_2eproto::InitDefaultsBrocast_Other_Prop_Change_23001Impl();
};
// -------------------------------------------------------------------

class Brocast_All_Eitities_Prop_23002 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:EntityMsg.Brocast_All_Eitities_Prop_23002) */ {
 public:
  Brocast_All_Eitities_Prop_23002();
  virtual ~Brocast_All_Eitities_Prop_23002();

  Brocast_All_Eitities_Prop_23002(const Brocast_All_Eitities_Prop_23002& from);

  inline Brocast_All_Eitities_Prop_23002& operator=(const Brocast_All_Eitities_Prop_23002& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Brocast_All_Eitities_Prop_23002(Brocast_All_Eitities_Prop_23002&& from) noexcept
    : Brocast_All_Eitities_Prop_23002() {
    *this = ::std::move(from);
  }

  inline Brocast_All_Eitities_Prop_23002& operator=(Brocast_All_Eitities_Prop_23002&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Brocast_All_Eitities_Prop_23002& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Brocast_All_Eitities_Prop_23002* internal_default_instance() {
    return reinterpret_cast<const Brocast_All_Eitities_Prop_23002*>(
               &_Brocast_All_Eitities_Prop_23002_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(Brocast_All_Eitities_Prop_23002* other);
  friend void swap(Brocast_All_Eitities_Prop_23002& a, Brocast_All_Eitities_Prop_23002& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Brocast_All_Eitities_Prop_23002* New() const PROTOBUF_FINAL { return New(NULL); }

  Brocast_All_Eitities_Prop_23002* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Brocast_All_Eitities_Prop_23002& from);
  void MergeFrom(const Brocast_All_Eitities_Prop_23002& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Brocast_All_Eitities_Prop_23002* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .EntityMsg.Struct_Entity_Properties EntitiesProps = 1;
  int entitiesprops_size() const;
  void clear_entitiesprops();
  static const int kEntitiesPropsFieldNumber = 1;
  const ::EntityMsg::Struct_Entity_Properties& entitiesprops(int index) const;
  ::EntityMsg::Struct_Entity_Properties* mutable_entitiesprops(int index);
  ::EntityMsg::Struct_Entity_Properties* add_entitiesprops();
  ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Entity_Properties >*
      mutable_entitiesprops();
  const ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Entity_Properties >&
      entitiesprops() const;

  // string Message = 3;
  void clear_message();
  static const int kMessageFieldNumber = 3;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int32 RpcId = 2;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 2;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // int32 Error = 4;
  void clear_error();
  static const int kErrorFieldNumber = 4;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:EntityMsg.Brocast_All_Eitities_Prop_23002)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Entity_Properties > entitiesprops_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  mutable int _cached_size_;
  friend struct ::protobuf_entity_2eproto::TableStruct;
  friend void ::protobuf_entity_2eproto::InitDefaultsBrocast_All_Eitities_Prop_23002Impl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Struct_Property

// int32 PropID = 1;
inline void Struct_Property::clear_propid() {
  propid_ = 0;
}
inline ::google::protobuf::int32 Struct_Property::propid() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Struct_Property.PropID)
  return propid_;
}
inline void Struct_Property::set_propid(::google::protobuf::int32 value) {
  
  propid_ = value;
  // @@protoc_insertion_point(field_set:EntityMsg.Struct_Property.PropID)
}

// int32 Value = 2;
inline void Struct_Property::clear_value() {
  value_ = 0;
}
inline ::google::protobuf::int32 Struct_Property::value() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Struct_Property.Value)
  return value_;
}
inline void Struct_Property::set_value(::google::protobuf::int32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:EntityMsg.Struct_Property.Value)
}

// -------------------------------------------------------------------

// Struct_Entity_Properties

// int64 entityUUID = 1;
inline void Struct_Entity_Properties::clear_entityuuid() {
  entityuuid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Struct_Entity_Properties::entityuuid() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Struct_Entity_Properties.entityUUID)
  return entityuuid_;
}
inline void Struct_Entity_Properties::set_entityuuid(::google::protobuf::int64 value) {
  
  entityuuid_ = value;
  // @@protoc_insertion_point(field_set:EntityMsg.Struct_Entity_Properties.entityUUID)
}

// repeated .EntityMsg.Struct_Property properties = 2;
inline int Struct_Entity_Properties::properties_size() const {
  return properties_.size();
}
inline void Struct_Entity_Properties::clear_properties() {
  properties_.Clear();
}
inline const ::EntityMsg::Struct_Property& Struct_Entity_Properties::properties(int index) const {
  // @@protoc_insertion_point(field_get:EntityMsg.Struct_Entity_Properties.properties)
  return properties_.Get(index);
}
inline ::EntityMsg::Struct_Property* Struct_Entity_Properties::mutable_properties(int index) {
  // @@protoc_insertion_point(field_mutable:EntityMsg.Struct_Entity_Properties.properties)
  return properties_.Mutable(index);
}
inline ::EntityMsg::Struct_Property* Struct_Entity_Properties::add_properties() {
  // @@protoc_insertion_point(field_add:EntityMsg.Struct_Entity_Properties.properties)
  return properties_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property >*
Struct_Entity_Properties::mutable_properties() {
  // @@protoc_insertion_point(field_mutable_list:EntityMsg.Struct_Entity_Properties.properties)
  return &properties_;
}
inline const ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property >&
Struct_Entity_Properties::properties() const {
  // @@protoc_insertion_point(field_list:EntityMsg.Struct_Entity_Properties.properties)
  return properties_;
}

// -------------------------------------------------------------------

// Notify_Self_Prop_Change_23000

// int64 PlayerID = 1;
inline void Notify_Self_Prop_Change_23000::clear_playerid() {
  playerid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Notify_Self_Prop_Change_23000::playerid() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Notify_Self_Prop_Change_23000.PlayerID)
  return playerid_;
}
inline void Notify_Self_Prop_Change_23000::set_playerid(::google::protobuf::int64 value) {
  
  playerid_ = value;
  // @@protoc_insertion_point(field_set:EntityMsg.Notify_Self_Prop_Change_23000.PlayerID)
}

// repeated .EntityMsg.Struct_Property changedProps = 2;
inline int Notify_Self_Prop_Change_23000::changedprops_size() const {
  return changedprops_.size();
}
inline void Notify_Self_Prop_Change_23000::clear_changedprops() {
  changedprops_.Clear();
}
inline const ::EntityMsg::Struct_Property& Notify_Self_Prop_Change_23000::changedprops(int index) const {
  // @@protoc_insertion_point(field_get:EntityMsg.Notify_Self_Prop_Change_23000.changedProps)
  return changedprops_.Get(index);
}
inline ::EntityMsg::Struct_Property* Notify_Self_Prop_Change_23000::mutable_changedprops(int index) {
  // @@protoc_insertion_point(field_mutable:EntityMsg.Notify_Self_Prop_Change_23000.changedProps)
  return changedprops_.Mutable(index);
}
inline ::EntityMsg::Struct_Property* Notify_Self_Prop_Change_23000::add_changedprops() {
  // @@protoc_insertion_point(field_add:EntityMsg.Notify_Self_Prop_Change_23000.changedProps)
  return changedprops_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property >*
Notify_Self_Prop_Change_23000::mutable_changedprops() {
  // @@protoc_insertion_point(field_mutable_list:EntityMsg.Notify_Self_Prop_Change_23000.changedProps)
  return &changedprops_;
}
inline const ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property >&
Notify_Self_Prop_Change_23000::changedprops() const {
  // @@protoc_insertion_point(field_list:EntityMsg.Notify_Self_Prop_Change_23000.changedProps)
  return changedprops_;
}

// int32 RpcId = 3;
inline void Notify_Self_Prop_Change_23000::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 Notify_Self_Prop_Change_23000::rpcid() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Notify_Self_Prop_Change_23000.RpcId)
  return rpcid_;
}
inline void Notify_Self_Prop_Change_23000::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:EntityMsg.Notify_Self_Prop_Change_23000.RpcId)
}

// string Message = 4;
inline void Notify_Self_Prop_Change_23000::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Notify_Self_Prop_Change_23000::message() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Notify_Self_Prop_Change_23000.Message)
  return message_.GetNoArena();
}
inline void Notify_Self_Prop_Change_23000::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:EntityMsg.Notify_Self_Prop_Change_23000.Message)
}
#if LANG_CXX11
inline void Notify_Self_Prop_Change_23000::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:EntityMsg.Notify_Self_Prop_Change_23000.Message)
}
#endif
inline void Notify_Self_Prop_Change_23000::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:EntityMsg.Notify_Self_Prop_Change_23000.Message)
}
inline void Notify_Self_Prop_Change_23000::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:EntityMsg.Notify_Self_Prop_Change_23000.Message)
}
inline ::std::string* Notify_Self_Prop_Change_23000::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:EntityMsg.Notify_Self_Prop_Change_23000.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Notify_Self_Prop_Change_23000::release_message() {
  // @@protoc_insertion_point(field_release:EntityMsg.Notify_Self_Prop_Change_23000.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Notify_Self_Prop_Change_23000::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:EntityMsg.Notify_Self_Prop_Change_23000.Message)
}

// int32 Error = 5;
inline void Notify_Self_Prop_Change_23000::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 Notify_Self_Prop_Change_23000::error() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Notify_Self_Prop_Change_23000.Error)
  return error_;
}
inline void Notify_Self_Prop_Change_23000::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:EntityMsg.Notify_Self_Prop_Change_23000.Error)
}

// -------------------------------------------------------------------

// Brocast_Other_Prop_Change_23001

// int64 entityUUID = 1;
inline void Brocast_Other_Prop_Change_23001::clear_entityuuid() {
  entityuuid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Brocast_Other_Prop_Change_23001::entityuuid() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Brocast_Other_Prop_Change_23001.entityUUID)
  return entityuuid_;
}
inline void Brocast_Other_Prop_Change_23001::set_entityuuid(::google::protobuf::int64 value) {
  
  entityuuid_ = value;
  // @@protoc_insertion_point(field_set:EntityMsg.Brocast_Other_Prop_Change_23001.entityUUID)
}

// repeated .EntityMsg.Struct_Property changedProps = 2;
inline int Brocast_Other_Prop_Change_23001::changedprops_size() const {
  return changedprops_.size();
}
inline void Brocast_Other_Prop_Change_23001::clear_changedprops() {
  changedprops_.Clear();
}
inline const ::EntityMsg::Struct_Property& Brocast_Other_Prop_Change_23001::changedprops(int index) const {
  // @@protoc_insertion_point(field_get:EntityMsg.Brocast_Other_Prop_Change_23001.changedProps)
  return changedprops_.Get(index);
}
inline ::EntityMsg::Struct_Property* Brocast_Other_Prop_Change_23001::mutable_changedprops(int index) {
  // @@protoc_insertion_point(field_mutable:EntityMsg.Brocast_Other_Prop_Change_23001.changedProps)
  return changedprops_.Mutable(index);
}
inline ::EntityMsg::Struct_Property* Brocast_Other_Prop_Change_23001::add_changedprops() {
  // @@protoc_insertion_point(field_add:EntityMsg.Brocast_Other_Prop_Change_23001.changedProps)
  return changedprops_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property >*
Brocast_Other_Prop_Change_23001::mutable_changedprops() {
  // @@protoc_insertion_point(field_mutable_list:EntityMsg.Brocast_Other_Prop_Change_23001.changedProps)
  return &changedprops_;
}
inline const ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Property >&
Brocast_Other_Prop_Change_23001::changedprops() const {
  // @@protoc_insertion_point(field_list:EntityMsg.Brocast_Other_Prop_Change_23001.changedProps)
  return changedprops_;
}

// int32 RpcId = 3;
inline void Brocast_Other_Prop_Change_23001::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 Brocast_Other_Prop_Change_23001::rpcid() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Brocast_Other_Prop_Change_23001.RpcId)
  return rpcid_;
}
inline void Brocast_Other_Prop_Change_23001::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:EntityMsg.Brocast_Other_Prop_Change_23001.RpcId)
}

// string Message = 4;
inline void Brocast_Other_Prop_Change_23001::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Brocast_Other_Prop_Change_23001::message() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Brocast_Other_Prop_Change_23001.Message)
  return message_.GetNoArena();
}
inline void Brocast_Other_Prop_Change_23001::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:EntityMsg.Brocast_Other_Prop_Change_23001.Message)
}
#if LANG_CXX11
inline void Brocast_Other_Prop_Change_23001::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:EntityMsg.Brocast_Other_Prop_Change_23001.Message)
}
#endif
inline void Brocast_Other_Prop_Change_23001::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:EntityMsg.Brocast_Other_Prop_Change_23001.Message)
}
inline void Brocast_Other_Prop_Change_23001::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:EntityMsg.Brocast_Other_Prop_Change_23001.Message)
}
inline ::std::string* Brocast_Other_Prop_Change_23001::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:EntityMsg.Brocast_Other_Prop_Change_23001.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Brocast_Other_Prop_Change_23001::release_message() {
  // @@protoc_insertion_point(field_release:EntityMsg.Brocast_Other_Prop_Change_23001.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Brocast_Other_Prop_Change_23001::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:EntityMsg.Brocast_Other_Prop_Change_23001.Message)
}

// int32 Error = 5;
inline void Brocast_Other_Prop_Change_23001::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 Brocast_Other_Prop_Change_23001::error() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Brocast_Other_Prop_Change_23001.Error)
  return error_;
}
inline void Brocast_Other_Prop_Change_23001::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:EntityMsg.Brocast_Other_Prop_Change_23001.Error)
}

// -------------------------------------------------------------------

// Brocast_All_Eitities_Prop_23002

// repeated .EntityMsg.Struct_Entity_Properties EntitiesProps = 1;
inline int Brocast_All_Eitities_Prop_23002::entitiesprops_size() const {
  return entitiesprops_.size();
}
inline void Brocast_All_Eitities_Prop_23002::clear_entitiesprops() {
  entitiesprops_.Clear();
}
inline const ::EntityMsg::Struct_Entity_Properties& Brocast_All_Eitities_Prop_23002::entitiesprops(int index) const {
  // @@protoc_insertion_point(field_get:EntityMsg.Brocast_All_Eitities_Prop_23002.EntitiesProps)
  return entitiesprops_.Get(index);
}
inline ::EntityMsg::Struct_Entity_Properties* Brocast_All_Eitities_Prop_23002::mutable_entitiesprops(int index) {
  // @@protoc_insertion_point(field_mutable:EntityMsg.Brocast_All_Eitities_Prop_23002.EntitiesProps)
  return entitiesprops_.Mutable(index);
}
inline ::EntityMsg::Struct_Entity_Properties* Brocast_All_Eitities_Prop_23002::add_entitiesprops() {
  // @@protoc_insertion_point(field_add:EntityMsg.Brocast_All_Eitities_Prop_23002.EntitiesProps)
  return entitiesprops_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Entity_Properties >*
Brocast_All_Eitities_Prop_23002::mutable_entitiesprops() {
  // @@protoc_insertion_point(field_mutable_list:EntityMsg.Brocast_All_Eitities_Prop_23002.EntitiesProps)
  return &entitiesprops_;
}
inline const ::google::protobuf::RepeatedPtrField< ::EntityMsg::Struct_Entity_Properties >&
Brocast_All_Eitities_Prop_23002::entitiesprops() const {
  // @@protoc_insertion_point(field_list:EntityMsg.Brocast_All_Eitities_Prop_23002.EntitiesProps)
  return entitiesprops_;
}

// int32 RpcId = 2;
inline void Brocast_All_Eitities_Prop_23002::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 Brocast_All_Eitities_Prop_23002::rpcid() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Brocast_All_Eitities_Prop_23002.RpcId)
  return rpcid_;
}
inline void Brocast_All_Eitities_Prop_23002::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:EntityMsg.Brocast_All_Eitities_Prop_23002.RpcId)
}

// string Message = 3;
inline void Brocast_All_Eitities_Prop_23002::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Brocast_All_Eitities_Prop_23002::message() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Brocast_All_Eitities_Prop_23002.Message)
  return message_.GetNoArena();
}
inline void Brocast_All_Eitities_Prop_23002::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:EntityMsg.Brocast_All_Eitities_Prop_23002.Message)
}
#if LANG_CXX11
inline void Brocast_All_Eitities_Prop_23002::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:EntityMsg.Brocast_All_Eitities_Prop_23002.Message)
}
#endif
inline void Brocast_All_Eitities_Prop_23002::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:EntityMsg.Brocast_All_Eitities_Prop_23002.Message)
}
inline void Brocast_All_Eitities_Prop_23002::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:EntityMsg.Brocast_All_Eitities_Prop_23002.Message)
}
inline ::std::string* Brocast_All_Eitities_Prop_23002::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:EntityMsg.Brocast_All_Eitities_Prop_23002.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Brocast_All_Eitities_Prop_23002::release_message() {
  // @@protoc_insertion_point(field_release:EntityMsg.Brocast_All_Eitities_Prop_23002.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Brocast_All_Eitities_Prop_23002::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:EntityMsg.Brocast_All_Eitities_Prop_23002.Message)
}

// int32 Error = 4;
inline void Brocast_All_Eitities_Prop_23002::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 Brocast_All_Eitities_Prop_23002::error() const {
  // @@protoc_insertion_point(field_get:EntityMsg.Brocast_All_Eitities_Prop_23002.Error)
  return error_;
}
inline void Brocast_All_Eitities_Prop_23002::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:EntityMsg.Brocast_All_Eitities_Prop_23002.Error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace EntityMsg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_entity_2eproto__INCLUDED
