// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

#include "login.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

//begin custom modify
#if defined(_MSC_VER)
#pragma warning(disable:4125)
#endif // _MSC_VER
//end custom modify
namespace login {
class Login_HeartBeat_Request_30DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Login_HeartBeat_Request_30>
      _instance;
} _Login_HeartBeat_Request_30_default_instance_;
class Login_RegisterAccount_Request_21000DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Login_RegisterAccount_Request_21000>
      _instance;
} _Login_RegisterAccount_Request_21000_default_instance_;
class Login_RegisterAccount_Response_21001DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Login_RegisterAccount_Response_21001>
      _instance;
} _Login_RegisterAccount_Response_21001_default_instance_;
class Login_LoginServer_Request_21002DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Login_LoginServer_Request_21002>
      _instance;
} _Login_LoginServer_Request_21002_default_instance_;
class Login_LoginServer_Response_21003DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Login_LoginServer_Response_21003>
      _instance;
} _Login_LoginServer_Response_21003_default_instance_;
}  // namespace login
namespace protobuf_login_2eproto {
void InitDefaultsLogin_HeartBeat_Request_30Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::login::_Login_HeartBeat_Request_30_default_instance_;
    new (ptr) ::login::Login_HeartBeat_Request_30();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::login::Login_HeartBeat_Request_30::InitAsDefaultInstance();
}

void InitDefaultsLogin_HeartBeat_Request_30() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsLogin_HeartBeat_Request_30Impl);
}

void InitDefaultsLogin_RegisterAccount_Request_21000Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::login::_Login_RegisterAccount_Request_21000_default_instance_;
    new (ptr) ::login::Login_RegisterAccount_Request_21000();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::login::Login_RegisterAccount_Request_21000::InitAsDefaultInstance();
}

void InitDefaultsLogin_RegisterAccount_Request_21000() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsLogin_RegisterAccount_Request_21000Impl);
}

void InitDefaultsLogin_RegisterAccount_Response_21001Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::login::_Login_RegisterAccount_Response_21001_default_instance_;
    new (ptr) ::login::Login_RegisterAccount_Response_21001();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::login::Login_RegisterAccount_Response_21001::InitAsDefaultInstance();
}

void InitDefaultsLogin_RegisterAccount_Response_21001() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsLogin_RegisterAccount_Response_21001Impl);
}

void InitDefaultsLogin_LoginServer_Request_21002Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::login::_Login_LoginServer_Request_21002_default_instance_;
    new (ptr) ::login::Login_LoginServer_Request_21002();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::login::Login_LoginServer_Request_21002::InitAsDefaultInstance();
}

void InitDefaultsLogin_LoginServer_Request_21002() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsLogin_LoginServer_Request_21002Impl);
}

void InitDefaultsLogin_LoginServer_Response_21003Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::login::_Login_LoginServer_Response_21003_default_instance_;
    new (ptr) ::login::Login_LoginServer_Response_21003();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::login::Login_LoginServer_Response_21003::InitAsDefaultInstance();
}

void InitDefaultsLogin_LoginServer_Response_21003() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsLogin_LoginServer_Response_21003Impl);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_HeartBeat_Request_30, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_RegisterAccount_Request_21000, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_RegisterAccount_Request_21000, accouent_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_RegisterAccount_Request_21000, password_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_RegisterAccount_Request_21000, rpcid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_RegisterAccount_Request_21000, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_RegisterAccount_Request_21000, error_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_RegisterAccount_Response_21001, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_RegisterAccount_Response_21001, rpcid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_RegisterAccount_Response_21001, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_RegisterAccount_Response_21001, error_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_LoginServer_Request_21002, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_LoginServer_Request_21002, accouent_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_LoginServer_Request_21002, password_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_LoginServer_Request_21002, rpcid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_LoginServer_Request_21002, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_LoginServer_Request_21002, error_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_LoginServer_Response_21003, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_LoginServer_Response_21003, sessionid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_LoginServer_Response_21003, rpcid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_LoginServer_Response_21003, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::login::Login_LoginServer_Response_21003, error_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::login::Login_HeartBeat_Request_30)},
  { 5, -1, sizeof(::login::Login_RegisterAccount_Request_21000)},
  { 15, -1, sizeof(::login::Login_RegisterAccount_Response_21001)},
  { 23, -1, sizeof(::login::Login_LoginServer_Request_21002)},
  { 33, -1, sizeof(::login::Login_LoginServer_Response_21003)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::login::_Login_HeartBeat_Request_30_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::login::_Login_RegisterAccount_Request_21000_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::login::_Login_RegisterAccount_Response_21001_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::login::_Login_LoginServer_Request_21002_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::login::_Login_LoginServer_Response_21003_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "login.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013login.proto\022\005login\"\034\n\032Login_HeartBeat_"
      "Request_30\"x\n#Login_RegisterAccount_Requ"
      "est_21000\022\020\n\010accouent\030\001 \001(\t\022\020\n\010password\030"
      "\002 \001(\t\022\r\n\005RpcId\030\003 \001(\005\022\017\n\007Message\030\004 \001(\t\022\r\n"
      "\005Error\030\005 \001(\005\"U\n$Login_RegisterAccount_Re"
      "sponse_21001\022\r\n\005RpcId\030\001 \001(\005\022\017\n\007Message\030\002"
      " \001(\t\022\r\n\005Error\030\003 \001(\005\"t\n\037Login_LoginServer"
      "_Request_21002\022\020\n\010accouent\030\001 \001(\t\022\020\n\010pass"
      "word\030\002 \001(\t\022\r\n\005RpcId\030\003 \001(\005\022\017\n\007Message\030\004 \001"
      "(\t\022\r\n\005Error\030\005 \001(\005\"d\n Login_LoginServer_R"
      "esponse_21003\022\021\n\tSessionID\030\001 \001(\005\022\r\n\005RpcI"
      "d\030\002 \001(\005\022\017\n\007Message\030\003 \001(\t\022\r\n\005Error\030\004 \001(\005b"
      "\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 487);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "login.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_login_2eproto
namespace login {

// ===================================================================

void Login_HeartBeat_Request_30::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Login_HeartBeat_Request_30::Login_HeartBeat_Request_30()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_login_2eproto::InitDefaultsLogin_HeartBeat_Request_30();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:login.Login_HeartBeat_Request_30)
}
Login_HeartBeat_Request_30::Login_HeartBeat_Request_30(const Login_HeartBeat_Request_30& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:login.Login_HeartBeat_Request_30)
}

void Login_HeartBeat_Request_30::SharedCtor() {
  _cached_size_ = 0;
}

Login_HeartBeat_Request_30::~Login_HeartBeat_Request_30() {
  // @@protoc_insertion_point(destructor:login.Login_HeartBeat_Request_30)
  SharedDtor();
}

void Login_HeartBeat_Request_30::SharedDtor() {
}

void Login_HeartBeat_Request_30::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Login_HeartBeat_Request_30::descriptor() {
  ::protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Login_HeartBeat_Request_30& Login_HeartBeat_Request_30::default_instance() {
  ::protobuf_login_2eproto::InitDefaultsLogin_HeartBeat_Request_30();
  return *internal_default_instance();
}

Login_HeartBeat_Request_30* Login_HeartBeat_Request_30::New(::google::protobuf::Arena* arena) const {
  Login_HeartBeat_Request_30* n = new Login_HeartBeat_Request_30;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Login_HeartBeat_Request_30::Clear() {
// @@protoc_insertion_point(message_clear_start:login.Login_HeartBeat_Request_30)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool Login_HeartBeat_Request_30::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:login.Login_HeartBeat_Request_30)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:login.Login_HeartBeat_Request_30)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:login.Login_HeartBeat_Request_30)
  return false;
#undef DO_
}

void Login_HeartBeat_Request_30::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:login.Login_HeartBeat_Request_30)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:login.Login_HeartBeat_Request_30)
}

::google::protobuf::uint8* Login_HeartBeat_Request_30::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:login.Login_HeartBeat_Request_30)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:login.Login_HeartBeat_Request_30)
  return target;
}

size_t Login_HeartBeat_Request_30::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:login.Login_HeartBeat_Request_30)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Login_HeartBeat_Request_30::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:login.Login_HeartBeat_Request_30)
  GOOGLE_DCHECK_NE(&from, this);
  const Login_HeartBeat_Request_30* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Login_HeartBeat_Request_30>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:login.Login_HeartBeat_Request_30)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:login.Login_HeartBeat_Request_30)
    MergeFrom(*source);
  }
}

void Login_HeartBeat_Request_30::MergeFrom(const Login_HeartBeat_Request_30& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:login.Login_HeartBeat_Request_30)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void Login_HeartBeat_Request_30::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:login.Login_HeartBeat_Request_30)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Login_HeartBeat_Request_30::CopyFrom(const Login_HeartBeat_Request_30& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:login.Login_HeartBeat_Request_30)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Login_HeartBeat_Request_30::IsInitialized() const {
  return true;
}

void Login_HeartBeat_Request_30::Swap(Login_HeartBeat_Request_30* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Login_HeartBeat_Request_30::InternalSwap(Login_HeartBeat_Request_30* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Login_HeartBeat_Request_30::GetMetadata() const {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Login_RegisterAccount_Request_21000::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Login_RegisterAccount_Request_21000::kAccouentFieldNumber;
const int Login_RegisterAccount_Request_21000::kPasswordFieldNumber;
const int Login_RegisterAccount_Request_21000::kRpcIdFieldNumber;
const int Login_RegisterAccount_Request_21000::kMessageFieldNumber;
const int Login_RegisterAccount_Request_21000::kErrorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Login_RegisterAccount_Request_21000::Login_RegisterAccount_Request_21000()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_login_2eproto::InitDefaultsLogin_RegisterAccount_Request_21000();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:login.Login_RegisterAccount_Request_21000)
}
Login_RegisterAccount_Request_21000::Login_RegisterAccount_Request_21000(const Login_RegisterAccount_Request_21000& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  accouent_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.accouent().size() > 0) {
    accouent_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.accouent_);
  }
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.password().size() > 0) {
    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  ::memcpy(&rpcid_, &from.rpcid_,
    static_cast<size_t>(reinterpret_cast<char*>(&error_) -
    reinterpret_cast<char*>(&rpcid_)) + sizeof(error_));
  // @@protoc_insertion_point(copy_constructor:login.Login_RegisterAccount_Request_21000)
}

void Login_RegisterAccount_Request_21000::SharedCtor() {
  accouent_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&rpcid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&rpcid_)) + sizeof(error_));
  _cached_size_ = 0;
}

Login_RegisterAccount_Request_21000::~Login_RegisterAccount_Request_21000() {
  // @@protoc_insertion_point(destructor:login.Login_RegisterAccount_Request_21000)
  SharedDtor();
}

void Login_RegisterAccount_Request_21000::SharedDtor() {
  accouent_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Login_RegisterAccount_Request_21000::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Login_RegisterAccount_Request_21000::descriptor() {
  ::protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Login_RegisterAccount_Request_21000& Login_RegisterAccount_Request_21000::default_instance() {
  ::protobuf_login_2eproto::InitDefaultsLogin_RegisterAccount_Request_21000();
  return *internal_default_instance();
}

Login_RegisterAccount_Request_21000* Login_RegisterAccount_Request_21000::New(::google::protobuf::Arena* arena) const {
  Login_RegisterAccount_Request_21000* n = new Login_RegisterAccount_Request_21000;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Login_RegisterAccount_Request_21000::Clear() {
// @@protoc_insertion_point(message_clear_start:login.Login_RegisterAccount_Request_21000)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  accouent_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&rpcid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&rpcid_)) + sizeof(error_));
  _internal_metadata_.Clear();
}

bool Login_RegisterAccount_Request_21000::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:login.Login_RegisterAccount_Request_21000)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string accouent = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_accouent()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->accouent().data(), static_cast<int>(this->accouent().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "login.Login_RegisterAccount_Request_21000.accouent"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string password = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->password().data(), static_cast<int>(this->password().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "login.Login_RegisterAccount_Request_21000.password"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 RpcId = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rpcid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Message = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "login.Login_RegisterAccount_Request_21000.Message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 Error = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:login.Login_RegisterAccount_Request_21000)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:login.Login_RegisterAccount_Request_21000)
  return false;
#undef DO_
}

void Login_RegisterAccount_Request_21000::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:login.Login_RegisterAccount_Request_21000)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string accouent = 1;
  if (this->accouent().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->accouent().data(), static_cast<int>(this->accouent().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_RegisterAccount_Request_21000.accouent");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->accouent(), output);
  }

  // string password = 2;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_RegisterAccount_Request_21000.password");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->password(), output);
  }

  // int32 RpcId = 3;
  if (this->rpcid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->rpcid(), output);
  }

  // string Message = 4;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_RegisterAccount_Request_21000.Message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->message(), output);
  }

  // int32 Error = 5;
  if (this->error() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->error(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:login.Login_RegisterAccount_Request_21000)
}

::google::protobuf::uint8* Login_RegisterAccount_Request_21000::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:login.Login_RegisterAccount_Request_21000)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string accouent = 1;
  if (this->accouent().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->accouent().data(), static_cast<int>(this->accouent().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_RegisterAccount_Request_21000.accouent");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->accouent(), target);
  }

  // string password = 2;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_RegisterAccount_Request_21000.password");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->password(), target);
  }

  // int32 RpcId = 3;
  if (this->rpcid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->rpcid(), target);
  }

  // string Message = 4;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_RegisterAccount_Request_21000.Message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->message(), target);
  }

  // int32 Error = 5;
  if (this->error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->error(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:login.Login_RegisterAccount_Request_21000)
  return target;
}

size_t Login_RegisterAccount_Request_21000::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:login.Login_RegisterAccount_Request_21000)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string accouent = 1;
  if (this->accouent().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->accouent());
  }

  // string password = 2;
  if (this->password().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->password());
  }

  // string Message = 4;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // int32 RpcId = 3;
  if (this->rpcid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rpcid());
  }

  // int32 Error = 5;
  if (this->error() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Login_RegisterAccount_Request_21000::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:login.Login_RegisterAccount_Request_21000)
  GOOGLE_DCHECK_NE(&from, this);
  const Login_RegisterAccount_Request_21000* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Login_RegisterAccount_Request_21000>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:login.Login_RegisterAccount_Request_21000)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:login.Login_RegisterAccount_Request_21000)
    MergeFrom(*source);
  }
}

void Login_RegisterAccount_Request_21000::MergeFrom(const Login_RegisterAccount_Request_21000& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:login.Login_RegisterAccount_Request_21000)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.accouent().size() > 0) {

    accouent_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.accouent_);
  }
  if (from.password().size() > 0) {

    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.rpcid() != 0) {
    set_rpcid(from.rpcid());
  }
  if (from.error() != 0) {
    set_error(from.error());
  }
}

void Login_RegisterAccount_Request_21000::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:login.Login_RegisterAccount_Request_21000)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Login_RegisterAccount_Request_21000::CopyFrom(const Login_RegisterAccount_Request_21000& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:login.Login_RegisterAccount_Request_21000)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Login_RegisterAccount_Request_21000::IsInitialized() const {
  return true;
}

void Login_RegisterAccount_Request_21000::Swap(Login_RegisterAccount_Request_21000* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Login_RegisterAccount_Request_21000::InternalSwap(Login_RegisterAccount_Request_21000* other) {
  using std::swap;
  accouent_.Swap(&other->accouent_);
  password_.Swap(&other->password_);
  message_.Swap(&other->message_);
  swap(rpcid_, other->rpcid_);
  swap(error_, other->error_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Login_RegisterAccount_Request_21000::GetMetadata() const {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Login_RegisterAccount_Response_21001::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Login_RegisterAccount_Response_21001::kRpcIdFieldNumber;
const int Login_RegisterAccount_Response_21001::kMessageFieldNumber;
const int Login_RegisterAccount_Response_21001::kErrorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Login_RegisterAccount_Response_21001::Login_RegisterAccount_Response_21001()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_login_2eproto::InitDefaultsLogin_RegisterAccount_Response_21001();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:login.Login_RegisterAccount_Response_21001)
}
Login_RegisterAccount_Response_21001::Login_RegisterAccount_Response_21001(const Login_RegisterAccount_Response_21001& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  ::memcpy(&rpcid_, &from.rpcid_,
    static_cast<size_t>(reinterpret_cast<char*>(&error_) -
    reinterpret_cast<char*>(&rpcid_)) + sizeof(error_));
  // @@protoc_insertion_point(copy_constructor:login.Login_RegisterAccount_Response_21001)
}

void Login_RegisterAccount_Response_21001::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&rpcid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&rpcid_)) + sizeof(error_));
  _cached_size_ = 0;
}

Login_RegisterAccount_Response_21001::~Login_RegisterAccount_Response_21001() {
  // @@protoc_insertion_point(destructor:login.Login_RegisterAccount_Response_21001)
  SharedDtor();
}

void Login_RegisterAccount_Response_21001::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Login_RegisterAccount_Response_21001::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Login_RegisterAccount_Response_21001::descriptor() {
  ::protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Login_RegisterAccount_Response_21001& Login_RegisterAccount_Response_21001::default_instance() {
  ::protobuf_login_2eproto::InitDefaultsLogin_RegisterAccount_Response_21001();
  return *internal_default_instance();
}

Login_RegisterAccount_Response_21001* Login_RegisterAccount_Response_21001::New(::google::protobuf::Arena* arena) const {
  Login_RegisterAccount_Response_21001* n = new Login_RegisterAccount_Response_21001;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Login_RegisterAccount_Response_21001::Clear() {
// @@protoc_insertion_point(message_clear_start:login.Login_RegisterAccount_Response_21001)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&rpcid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&rpcid_)) + sizeof(error_));
  _internal_metadata_.Clear();
}

bool Login_RegisterAccount_Response_21001::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:login.Login_RegisterAccount_Response_21001)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 RpcId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rpcid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Message = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "login.Login_RegisterAccount_Response_21001.Message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 Error = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:login.Login_RegisterAccount_Response_21001)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:login.Login_RegisterAccount_Response_21001)
  return false;
#undef DO_
}

void Login_RegisterAccount_Response_21001::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:login.Login_RegisterAccount_Response_21001)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 RpcId = 1;
  if (this->rpcid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->rpcid(), output);
  }

  // string Message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_RegisterAccount_Response_21001.Message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->message(), output);
  }

  // int32 Error = 3;
  if (this->error() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->error(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:login.Login_RegisterAccount_Response_21001)
}

::google::protobuf::uint8* Login_RegisterAccount_Response_21001::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:login.Login_RegisterAccount_Response_21001)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 RpcId = 1;
  if (this->rpcid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->rpcid(), target);
  }

  // string Message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_RegisterAccount_Response_21001.Message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->message(), target);
  }

  // int32 Error = 3;
  if (this->error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->error(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:login.Login_RegisterAccount_Response_21001)
  return target;
}

size_t Login_RegisterAccount_Response_21001::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:login.Login_RegisterAccount_Response_21001)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string Message = 2;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // int32 RpcId = 1;
  if (this->rpcid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rpcid());
  }

  // int32 Error = 3;
  if (this->error() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Login_RegisterAccount_Response_21001::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:login.Login_RegisterAccount_Response_21001)
  GOOGLE_DCHECK_NE(&from, this);
  const Login_RegisterAccount_Response_21001* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Login_RegisterAccount_Response_21001>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:login.Login_RegisterAccount_Response_21001)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:login.Login_RegisterAccount_Response_21001)
    MergeFrom(*source);
  }
}

void Login_RegisterAccount_Response_21001::MergeFrom(const Login_RegisterAccount_Response_21001& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:login.Login_RegisterAccount_Response_21001)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.rpcid() != 0) {
    set_rpcid(from.rpcid());
  }
  if (from.error() != 0) {
    set_error(from.error());
  }
}

void Login_RegisterAccount_Response_21001::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:login.Login_RegisterAccount_Response_21001)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Login_RegisterAccount_Response_21001::CopyFrom(const Login_RegisterAccount_Response_21001& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:login.Login_RegisterAccount_Response_21001)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Login_RegisterAccount_Response_21001::IsInitialized() const {
  return true;
}

void Login_RegisterAccount_Response_21001::Swap(Login_RegisterAccount_Response_21001* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Login_RegisterAccount_Response_21001::InternalSwap(Login_RegisterAccount_Response_21001* other) {
  using std::swap;
  message_.Swap(&other->message_);
  swap(rpcid_, other->rpcid_);
  swap(error_, other->error_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Login_RegisterAccount_Response_21001::GetMetadata() const {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Login_LoginServer_Request_21002::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Login_LoginServer_Request_21002::kAccouentFieldNumber;
const int Login_LoginServer_Request_21002::kPasswordFieldNumber;
const int Login_LoginServer_Request_21002::kRpcIdFieldNumber;
const int Login_LoginServer_Request_21002::kMessageFieldNumber;
const int Login_LoginServer_Request_21002::kErrorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Login_LoginServer_Request_21002::Login_LoginServer_Request_21002()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_login_2eproto::InitDefaultsLogin_LoginServer_Request_21002();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:login.Login_LoginServer_Request_21002)
}
Login_LoginServer_Request_21002::Login_LoginServer_Request_21002(const Login_LoginServer_Request_21002& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  accouent_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.accouent().size() > 0) {
    accouent_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.accouent_);
  }
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.password().size() > 0) {
    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  ::memcpy(&rpcid_, &from.rpcid_,
    static_cast<size_t>(reinterpret_cast<char*>(&error_) -
    reinterpret_cast<char*>(&rpcid_)) + sizeof(error_));
  // @@protoc_insertion_point(copy_constructor:login.Login_LoginServer_Request_21002)
}

void Login_LoginServer_Request_21002::SharedCtor() {
  accouent_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&rpcid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&rpcid_)) + sizeof(error_));
  _cached_size_ = 0;
}

Login_LoginServer_Request_21002::~Login_LoginServer_Request_21002() {
  // @@protoc_insertion_point(destructor:login.Login_LoginServer_Request_21002)
  SharedDtor();
}

void Login_LoginServer_Request_21002::SharedDtor() {
  accouent_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Login_LoginServer_Request_21002::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Login_LoginServer_Request_21002::descriptor() {
  ::protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Login_LoginServer_Request_21002& Login_LoginServer_Request_21002::default_instance() {
  ::protobuf_login_2eproto::InitDefaultsLogin_LoginServer_Request_21002();
  return *internal_default_instance();
}

Login_LoginServer_Request_21002* Login_LoginServer_Request_21002::New(::google::protobuf::Arena* arena) const {
  Login_LoginServer_Request_21002* n = new Login_LoginServer_Request_21002;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Login_LoginServer_Request_21002::Clear() {
// @@protoc_insertion_point(message_clear_start:login.Login_LoginServer_Request_21002)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  accouent_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&rpcid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&rpcid_)) + sizeof(error_));
  _internal_metadata_.Clear();
}

bool Login_LoginServer_Request_21002::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:login.Login_LoginServer_Request_21002)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string accouent = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_accouent()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->accouent().data(), static_cast<int>(this->accouent().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "login.Login_LoginServer_Request_21002.accouent"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string password = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->password().data(), static_cast<int>(this->password().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "login.Login_LoginServer_Request_21002.password"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 RpcId = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rpcid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Message = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "login.Login_LoginServer_Request_21002.Message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 Error = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:login.Login_LoginServer_Request_21002)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:login.Login_LoginServer_Request_21002)
  return false;
#undef DO_
}

void Login_LoginServer_Request_21002::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:login.Login_LoginServer_Request_21002)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string accouent = 1;
  if (this->accouent().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->accouent().data(), static_cast<int>(this->accouent().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_LoginServer_Request_21002.accouent");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->accouent(), output);
  }

  // string password = 2;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_LoginServer_Request_21002.password");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->password(), output);
  }

  // int32 RpcId = 3;
  if (this->rpcid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->rpcid(), output);
  }

  // string Message = 4;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_LoginServer_Request_21002.Message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->message(), output);
  }

  // int32 Error = 5;
  if (this->error() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->error(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:login.Login_LoginServer_Request_21002)
}

::google::protobuf::uint8* Login_LoginServer_Request_21002::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:login.Login_LoginServer_Request_21002)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string accouent = 1;
  if (this->accouent().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->accouent().data(), static_cast<int>(this->accouent().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_LoginServer_Request_21002.accouent");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->accouent(), target);
  }

  // string password = 2;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_LoginServer_Request_21002.password");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->password(), target);
  }

  // int32 RpcId = 3;
  if (this->rpcid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->rpcid(), target);
  }

  // string Message = 4;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_LoginServer_Request_21002.Message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->message(), target);
  }

  // int32 Error = 5;
  if (this->error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->error(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:login.Login_LoginServer_Request_21002)
  return target;
}

size_t Login_LoginServer_Request_21002::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:login.Login_LoginServer_Request_21002)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string accouent = 1;
  if (this->accouent().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->accouent());
  }

  // string password = 2;
  if (this->password().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->password());
  }

  // string Message = 4;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // int32 RpcId = 3;
  if (this->rpcid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rpcid());
  }

  // int32 Error = 5;
  if (this->error() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Login_LoginServer_Request_21002::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:login.Login_LoginServer_Request_21002)
  GOOGLE_DCHECK_NE(&from, this);
  const Login_LoginServer_Request_21002* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Login_LoginServer_Request_21002>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:login.Login_LoginServer_Request_21002)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:login.Login_LoginServer_Request_21002)
    MergeFrom(*source);
  }
}

void Login_LoginServer_Request_21002::MergeFrom(const Login_LoginServer_Request_21002& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:login.Login_LoginServer_Request_21002)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.accouent().size() > 0) {

    accouent_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.accouent_);
  }
  if (from.password().size() > 0) {

    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.rpcid() != 0) {
    set_rpcid(from.rpcid());
  }
  if (from.error() != 0) {
    set_error(from.error());
  }
}

void Login_LoginServer_Request_21002::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:login.Login_LoginServer_Request_21002)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Login_LoginServer_Request_21002::CopyFrom(const Login_LoginServer_Request_21002& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:login.Login_LoginServer_Request_21002)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Login_LoginServer_Request_21002::IsInitialized() const {
  return true;
}

void Login_LoginServer_Request_21002::Swap(Login_LoginServer_Request_21002* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Login_LoginServer_Request_21002::InternalSwap(Login_LoginServer_Request_21002* other) {
  using std::swap;
  accouent_.Swap(&other->accouent_);
  password_.Swap(&other->password_);
  message_.Swap(&other->message_);
  swap(rpcid_, other->rpcid_);
  swap(error_, other->error_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Login_LoginServer_Request_21002::GetMetadata() const {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Login_LoginServer_Response_21003::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Login_LoginServer_Response_21003::kSessionIDFieldNumber;
const int Login_LoginServer_Response_21003::kRpcIdFieldNumber;
const int Login_LoginServer_Response_21003::kMessageFieldNumber;
const int Login_LoginServer_Response_21003::kErrorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Login_LoginServer_Response_21003::Login_LoginServer_Response_21003()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_login_2eproto::InitDefaultsLogin_LoginServer_Response_21003();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:login.Login_LoginServer_Response_21003)
}
Login_LoginServer_Response_21003::Login_LoginServer_Response_21003(const Login_LoginServer_Response_21003& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  ::memcpy(&sessionid_, &from.sessionid_,
    static_cast<size_t>(reinterpret_cast<char*>(&error_) -
    reinterpret_cast<char*>(&sessionid_)) + sizeof(error_));
  // @@protoc_insertion_point(copy_constructor:login.Login_LoginServer_Response_21003)
}

void Login_LoginServer_Response_21003::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&sessionid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&sessionid_)) + sizeof(error_));
  _cached_size_ = 0;
}

Login_LoginServer_Response_21003::~Login_LoginServer_Response_21003() {
  // @@protoc_insertion_point(destructor:login.Login_LoginServer_Response_21003)
  SharedDtor();
}

void Login_LoginServer_Response_21003::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Login_LoginServer_Response_21003::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Login_LoginServer_Response_21003::descriptor() {
  ::protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Login_LoginServer_Response_21003& Login_LoginServer_Response_21003::default_instance() {
  ::protobuf_login_2eproto::InitDefaultsLogin_LoginServer_Response_21003();
  return *internal_default_instance();
}

Login_LoginServer_Response_21003* Login_LoginServer_Response_21003::New(::google::protobuf::Arena* arena) const {
  Login_LoginServer_Response_21003* n = new Login_LoginServer_Response_21003;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Login_LoginServer_Response_21003::Clear() {
// @@protoc_insertion_point(message_clear_start:login.Login_LoginServer_Response_21003)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&sessionid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_) -
      reinterpret_cast<char*>(&sessionid_)) + sizeof(error_));
  _internal_metadata_.Clear();
}

bool Login_LoginServer_Response_21003::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:login.Login_LoginServer_Response_21003)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 SessionID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sessionid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 RpcId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rpcid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Message = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "login.Login_LoginServer_Response_21003.Message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 Error = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:login.Login_LoginServer_Response_21003)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:login.Login_LoginServer_Response_21003)
  return false;
#undef DO_
}

void Login_LoginServer_Response_21003::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:login.Login_LoginServer_Response_21003)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 SessionID = 1;
  if (this->sessionid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->sessionid(), output);
  }

  // int32 RpcId = 2;
  if (this->rpcid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->rpcid(), output);
  }

  // string Message = 3;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_LoginServer_Response_21003.Message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->message(), output);
  }

  // int32 Error = 4;
  if (this->error() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->error(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:login.Login_LoginServer_Response_21003)
}

::google::protobuf::uint8* Login_LoginServer_Response_21003::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:login.Login_LoginServer_Response_21003)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 SessionID = 1;
  if (this->sessionid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->sessionid(), target);
  }

  // int32 RpcId = 2;
  if (this->rpcid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->rpcid(), target);
  }

  // string Message = 3;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "login.Login_LoginServer_Response_21003.Message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->message(), target);
  }

  // int32 Error = 4;
  if (this->error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->error(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:login.Login_LoginServer_Response_21003)
  return target;
}

size_t Login_LoginServer_Response_21003::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:login.Login_LoginServer_Response_21003)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string Message = 3;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // int32 SessionID = 1;
  if (this->sessionid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sessionid());
  }

  // int32 RpcId = 2;
  if (this->rpcid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rpcid());
  }

  // int32 Error = 4;
  if (this->error() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Login_LoginServer_Response_21003::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:login.Login_LoginServer_Response_21003)
  GOOGLE_DCHECK_NE(&from, this);
  const Login_LoginServer_Response_21003* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Login_LoginServer_Response_21003>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:login.Login_LoginServer_Response_21003)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:login.Login_LoginServer_Response_21003)
    MergeFrom(*source);
  }
}

void Login_LoginServer_Response_21003::MergeFrom(const Login_LoginServer_Response_21003& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:login.Login_LoginServer_Response_21003)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.sessionid() != 0) {
    set_sessionid(from.sessionid());
  }
  if (from.rpcid() != 0) {
    set_rpcid(from.rpcid());
  }
  if (from.error() != 0) {
    set_error(from.error());
  }
}

void Login_LoginServer_Response_21003::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:login.Login_LoginServer_Response_21003)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Login_LoginServer_Response_21003::CopyFrom(const Login_LoginServer_Response_21003& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:login.Login_LoginServer_Response_21003)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Login_LoginServer_Response_21003::IsInitialized() const {
  return true;
}

void Login_LoginServer_Response_21003::Swap(Login_LoginServer_Response_21003* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Login_LoginServer_Response_21003::InternalSwap(Login_LoginServer_Response_21003* other) {
  using std::swap;
  message_.Swap(&other->message_);
  swap(sessionid_, other->sessionid_);
  swap(rpcid_, other->rpcid_);
  swap(error_, other->error_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Login_LoginServer_Response_21003::GetMetadata() const {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace login

// @@protoc_insertion_point(global_scope)
