// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

#ifndef PROTOBUF_login_2eproto__INCLUDED
#define PROTOBUF_login_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_login_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsLogin_HeartBeat_Request_30Impl();
void InitDefaultsLogin_HeartBeat_Request_30();
void InitDefaultsLogin_RegisterAccount_Request_21000Impl();
void InitDefaultsLogin_RegisterAccount_Request_21000();
void InitDefaultsLogin_RegisterAccount_Response_21001Impl();
void InitDefaultsLogin_RegisterAccount_Response_21001();
void InitDefaultsLogin_LoginServer_Request_21002Impl();
void InitDefaultsLogin_LoginServer_Request_21002();
void InitDefaultsLogin_LoginServer_Response_21003Impl();
void InitDefaultsLogin_LoginServer_Response_21003();
inline void InitDefaults() {
  InitDefaultsLogin_HeartBeat_Request_30();
  InitDefaultsLogin_RegisterAccount_Request_21000();
  InitDefaultsLogin_RegisterAccount_Response_21001();
  InitDefaultsLogin_LoginServer_Request_21002();
  InitDefaultsLogin_LoginServer_Response_21003();
}
}  // namespace protobuf_login_2eproto
namespace login {
class Login_HeartBeat_Request_30;
class Login_HeartBeat_Request_30DefaultTypeInternal;
extern Login_HeartBeat_Request_30DefaultTypeInternal _Login_HeartBeat_Request_30_default_instance_;
class Login_LoginServer_Request_21002;
class Login_LoginServer_Request_21002DefaultTypeInternal;
extern Login_LoginServer_Request_21002DefaultTypeInternal _Login_LoginServer_Request_21002_default_instance_;
class Login_LoginServer_Response_21003;
class Login_LoginServer_Response_21003DefaultTypeInternal;
extern Login_LoginServer_Response_21003DefaultTypeInternal _Login_LoginServer_Response_21003_default_instance_;
class Login_RegisterAccount_Request_21000;
class Login_RegisterAccount_Request_21000DefaultTypeInternal;
extern Login_RegisterAccount_Request_21000DefaultTypeInternal _Login_RegisterAccount_Request_21000_default_instance_;
class Login_RegisterAccount_Response_21001;
class Login_RegisterAccount_Response_21001DefaultTypeInternal;
extern Login_RegisterAccount_Response_21001DefaultTypeInternal _Login_RegisterAccount_Response_21001_default_instance_;
}  // namespace login
namespace login {

// ===================================================================

class Login_HeartBeat_Request_30 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_HeartBeat_Request_30) */ {
 public:
  Login_HeartBeat_Request_30();
  virtual ~Login_HeartBeat_Request_30();

  Login_HeartBeat_Request_30(const Login_HeartBeat_Request_30& from);

  inline Login_HeartBeat_Request_30& operator=(const Login_HeartBeat_Request_30& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Login_HeartBeat_Request_30(Login_HeartBeat_Request_30&& from) noexcept
    : Login_HeartBeat_Request_30() {
    *this = ::std::move(from);
  }

  inline Login_HeartBeat_Request_30& operator=(Login_HeartBeat_Request_30&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_HeartBeat_Request_30& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Login_HeartBeat_Request_30* internal_default_instance() {
    return reinterpret_cast<const Login_HeartBeat_Request_30*>(
               &_Login_HeartBeat_Request_30_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Login_HeartBeat_Request_30* other);
  friend void swap(Login_HeartBeat_Request_30& a, Login_HeartBeat_Request_30& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Login_HeartBeat_Request_30* New() const PROTOBUF_FINAL { return New(NULL); }

  Login_HeartBeat_Request_30* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Login_HeartBeat_Request_30& from);
  void MergeFrom(const Login_HeartBeat_Request_30& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Login_HeartBeat_Request_30* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:login.Login_HeartBeat_Request_30)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_login_2eproto::TableStruct;
  friend void ::protobuf_login_2eproto::InitDefaultsLogin_HeartBeat_Request_30Impl();
};
// -------------------------------------------------------------------

class Login_RegisterAccount_Request_21000 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_RegisterAccount_Request_21000) */ {
 public:
  Login_RegisterAccount_Request_21000();
  virtual ~Login_RegisterAccount_Request_21000();

  Login_RegisterAccount_Request_21000(const Login_RegisterAccount_Request_21000& from);

  inline Login_RegisterAccount_Request_21000& operator=(const Login_RegisterAccount_Request_21000& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Login_RegisterAccount_Request_21000(Login_RegisterAccount_Request_21000&& from) noexcept
    : Login_RegisterAccount_Request_21000() {
    *this = ::std::move(from);
  }

  inline Login_RegisterAccount_Request_21000& operator=(Login_RegisterAccount_Request_21000&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_RegisterAccount_Request_21000& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Login_RegisterAccount_Request_21000* internal_default_instance() {
    return reinterpret_cast<const Login_RegisterAccount_Request_21000*>(
               &_Login_RegisterAccount_Request_21000_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Login_RegisterAccount_Request_21000* other);
  friend void swap(Login_RegisterAccount_Request_21000& a, Login_RegisterAccount_Request_21000& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Login_RegisterAccount_Request_21000* New() const PROTOBUF_FINAL { return New(NULL); }

  Login_RegisterAccount_Request_21000* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Login_RegisterAccount_Request_21000& from);
  void MergeFrom(const Login_RegisterAccount_Request_21000& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Login_RegisterAccount_Request_21000* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string accouent = 1;
  void clear_accouent();
  static const int kAccouentFieldNumber = 1;
  const ::std::string& accouent() const;
  void set_accouent(const ::std::string& value);
  #if LANG_CXX11
  void set_accouent(::std::string&& value);
  #endif
  void set_accouent(const char* value);
  void set_accouent(const char* value, size_t size);
  ::std::string* mutable_accouent();
  ::std::string* release_accouent();
  void set_allocated_accouent(::std::string* accouent);

  // string password = 2;
  void clear_password();
  static const int kPasswordFieldNumber = 2;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // string Message = 4;
  void clear_message();
  static const int kMessageFieldNumber = 4;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int32 RpcId = 3;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 3;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // int32 Error = 5;
  void clear_error();
  static const int kErrorFieldNumber = 5;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:login.Login_RegisterAccount_Request_21000)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr accouent_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  mutable int _cached_size_;
  friend struct ::protobuf_login_2eproto::TableStruct;
  friend void ::protobuf_login_2eproto::InitDefaultsLogin_RegisterAccount_Request_21000Impl();
};
// -------------------------------------------------------------------

class Login_RegisterAccount_Response_21001 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_RegisterAccount_Response_21001) */ {
 public:
  Login_RegisterAccount_Response_21001();
  virtual ~Login_RegisterAccount_Response_21001();

  Login_RegisterAccount_Response_21001(const Login_RegisterAccount_Response_21001& from);

  inline Login_RegisterAccount_Response_21001& operator=(const Login_RegisterAccount_Response_21001& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Login_RegisterAccount_Response_21001(Login_RegisterAccount_Response_21001&& from) noexcept
    : Login_RegisterAccount_Response_21001() {
    *this = ::std::move(from);
  }

  inline Login_RegisterAccount_Response_21001& operator=(Login_RegisterAccount_Response_21001&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_RegisterAccount_Response_21001& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Login_RegisterAccount_Response_21001* internal_default_instance() {
    return reinterpret_cast<const Login_RegisterAccount_Response_21001*>(
               &_Login_RegisterAccount_Response_21001_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Login_RegisterAccount_Response_21001* other);
  friend void swap(Login_RegisterAccount_Response_21001& a, Login_RegisterAccount_Response_21001& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Login_RegisterAccount_Response_21001* New() const PROTOBUF_FINAL { return New(NULL); }

  Login_RegisterAccount_Response_21001* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Login_RegisterAccount_Response_21001& from);
  void MergeFrom(const Login_RegisterAccount_Response_21001& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Login_RegisterAccount_Response_21001* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string Message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int32 RpcId = 1;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 1;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // int32 Error = 3;
  void clear_error();
  static const int kErrorFieldNumber = 3;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:login.Login_RegisterAccount_Response_21001)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  mutable int _cached_size_;
  friend struct ::protobuf_login_2eproto::TableStruct;
  friend void ::protobuf_login_2eproto::InitDefaultsLogin_RegisterAccount_Response_21001Impl();
};
// -------------------------------------------------------------------

class Login_LoginServer_Request_21002 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_LoginServer_Request_21002) */ {
 public:
  Login_LoginServer_Request_21002();
  virtual ~Login_LoginServer_Request_21002();

  Login_LoginServer_Request_21002(const Login_LoginServer_Request_21002& from);

  inline Login_LoginServer_Request_21002& operator=(const Login_LoginServer_Request_21002& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Login_LoginServer_Request_21002(Login_LoginServer_Request_21002&& from) noexcept
    : Login_LoginServer_Request_21002() {
    *this = ::std::move(from);
  }

  inline Login_LoginServer_Request_21002& operator=(Login_LoginServer_Request_21002&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_LoginServer_Request_21002& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Login_LoginServer_Request_21002* internal_default_instance() {
    return reinterpret_cast<const Login_LoginServer_Request_21002*>(
               &_Login_LoginServer_Request_21002_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Login_LoginServer_Request_21002* other);
  friend void swap(Login_LoginServer_Request_21002& a, Login_LoginServer_Request_21002& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Login_LoginServer_Request_21002* New() const PROTOBUF_FINAL { return New(NULL); }

  Login_LoginServer_Request_21002* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Login_LoginServer_Request_21002& from);
  void MergeFrom(const Login_LoginServer_Request_21002& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Login_LoginServer_Request_21002* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string accouent = 1;
  void clear_accouent();
  static const int kAccouentFieldNumber = 1;
  const ::std::string& accouent() const;
  void set_accouent(const ::std::string& value);
  #if LANG_CXX11
  void set_accouent(::std::string&& value);
  #endif
  void set_accouent(const char* value);
  void set_accouent(const char* value, size_t size);
  ::std::string* mutable_accouent();
  ::std::string* release_accouent();
  void set_allocated_accouent(::std::string* accouent);

  // string password = 2;
  void clear_password();
  static const int kPasswordFieldNumber = 2;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // string Message = 4;
  void clear_message();
  static const int kMessageFieldNumber = 4;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int32 RpcId = 3;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 3;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // int32 Error = 5;
  void clear_error();
  static const int kErrorFieldNumber = 5;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:login.Login_LoginServer_Request_21002)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr accouent_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  mutable int _cached_size_;
  friend struct ::protobuf_login_2eproto::TableStruct;
  friend void ::protobuf_login_2eproto::InitDefaultsLogin_LoginServer_Request_21002Impl();
};
// -------------------------------------------------------------------

class Login_LoginServer_Response_21003 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_LoginServer_Response_21003) */ {
 public:
  Login_LoginServer_Response_21003();
  virtual ~Login_LoginServer_Response_21003();

  Login_LoginServer_Response_21003(const Login_LoginServer_Response_21003& from);

  inline Login_LoginServer_Response_21003& operator=(const Login_LoginServer_Response_21003& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Login_LoginServer_Response_21003(Login_LoginServer_Response_21003&& from) noexcept
    : Login_LoginServer_Response_21003() {
    *this = ::std::move(from);
  }

  inline Login_LoginServer_Response_21003& operator=(Login_LoginServer_Response_21003&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_LoginServer_Response_21003& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Login_LoginServer_Response_21003* internal_default_instance() {
    return reinterpret_cast<const Login_LoginServer_Response_21003*>(
               &_Login_LoginServer_Response_21003_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(Login_LoginServer_Response_21003* other);
  friend void swap(Login_LoginServer_Response_21003& a, Login_LoginServer_Response_21003& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Login_LoginServer_Response_21003* New() const PROTOBUF_FINAL { return New(NULL); }

  Login_LoginServer_Response_21003* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Login_LoginServer_Response_21003& from);
  void MergeFrom(const Login_LoginServer_Response_21003& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Login_LoginServer_Response_21003* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string Message = 3;
  void clear_message();
  static const int kMessageFieldNumber = 3;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // int32 SessionID = 1;
  void clear_sessionid();
  static const int kSessionIDFieldNumber = 1;
  ::google::protobuf::int32 sessionid() const;
  void set_sessionid(::google::protobuf::int32 value);

  // int32 RpcId = 2;
  void clear_rpcid();
  static const int kRpcIdFieldNumber = 2;
  ::google::protobuf::int32 rpcid() const;
  void set_rpcid(::google::protobuf::int32 value);

  // int32 Error = 4;
  void clear_error();
  static const int kErrorFieldNumber = 4;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:login.Login_LoginServer_Response_21003)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 sessionid_;
  ::google::protobuf::int32 rpcid_;
  ::google::protobuf::int32 error_;
  mutable int _cached_size_;
  friend struct ::protobuf_login_2eproto::TableStruct;
  friend void ::protobuf_login_2eproto::InitDefaultsLogin_LoginServer_Response_21003Impl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Login_HeartBeat_Request_30

// -------------------------------------------------------------------

// Login_RegisterAccount_Request_21000

// string accouent = 1;
inline void Login_RegisterAccount_Request_21000::clear_accouent() {
  accouent_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_RegisterAccount_Request_21000::accouent() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterAccount_Request_21000.accouent)
  return accouent_.GetNoArena();
}
inline void Login_RegisterAccount_Request_21000::set_accouent(const ::std::string& value) {
  
  accouent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_RegisterAccount_Request_21000.accouent)
}
#if LANG_CXX11
inline void Login_RegisterAccount_Request_21000::set_accouent(::std::string&& value) {
  
  accouent_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:login.Login_RegisterAccount_Request_21000.accouent)
}
#endif
inline void Login_RegisterAccount_Request_21000::set_accouent(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  accouent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_RegisterAccount_Request_21000.accouent)
}
inline void Login_RegisterAccount_Request_21000::set_accouent(const char* value, size_t size) {
  
  accouent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_RegisterAccount_Request_21000.accouent)
}
inline ::std::string* Login_RegisterAccount_Request_21000::mutable_accouent() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_RegisterAccount_Request_21000.accouent)
  return accouent_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_RegisterAccount_Request_21000::release_accouent() {
  // @@protoc_insertion_point(field_release:login.Login_RegisterAccount_Request_21000.accouent)
  
  return accouent_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_RegisterAccount_Request_21000::set_allocated_accouent(::std::string* accouent) {
  if (accouent != NULL) {
    
  } else {
    
  }
  accouent_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), accouent);
  // @@protoc_insertion_point(field_set_allocated:login.Login_RegisterAccount_Request_21000.accouent)
}

// string password = 2;
inline void Login_RegisterAccount_Request_21000::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_RegisterAccount_Request_21000::password() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterAccount_Request_21000.password)
  return password_.GetNoArena();
}
inline void Login_RegisterAccount_Request_21000::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_RegisterAccount_Request_21000.password)
}
#if LANG_CXX11
inline void Login_RegisterAccount_Request_21000::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:login.Login_RegisterAccount_Request_21000.password)
}
#endif
inline void Login_RegisterAccount_Request_21000::set_password(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_RegisterAccount_Request_21000.password)
}
inline void Login_RegisterAccount_Request_21000::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_RegisterAccount_Request_21000.password)
}
inline ::std::string* Login_RegisterAccount_Request_21000::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_RegisterAccount_Request_21000.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_RegisterAccount_Request_21000::release_password() {
  // @@protoc_insertion_point(field_release:login.Login_RegisterAccount_Request_21000.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_RegisterAccount_Request_21000::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:login.Login_RegisterAccount_Request_21000.password)
}

// int32 RpcId = 3;
inline void Login_RegisterAccount_Request_21000::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 Login_RegisterAccount_Request_21000::rpcid() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterAccount_Request_21000.RpcId)
  return rpcid_;
}
inline void Login_RegisterAccount_Request_21000::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:login.Login_RegisterAccount_Request_21000.RpcId)
}

// string Message = 4;
inline void Login_RegisterAccount_Request_21000::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_RegisterAccount_Request_21000::message() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterAccount_Request_21000.Message)
  return message_.GetNoArena();
}
inline void Login_RegisterAccount_Request_21000::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_RegisterAccount_Request_21000.Message)
}
#if LANG_CXX11
inline void Login_RegisterAccount_Request_21000::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:login.Login_RegisterAccount_Request_21000.Message)
}
#endif
inline void Login_RegisterAccount_Request_21000::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_RegisterAccount_Request_21000.Message)
}
inline void Login_RegisterAccount_Request_21000::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_RegisterAccount_Request_21000.Message)
}
inline ::std::string* Login_RegisterAccount_Request_21000::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_RegisterAccount_Request_21000.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_RegisterAccount_Request_21000::release_message() {
  // @@protoc_insertion_point(field_release:login.Login_RegisterAccount_Request_21000.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_RegisterAccount_Request_21000::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:login.Login_RegisterAccount_Request_21000.Message)
}

// int32 Error = 5;
inline void Login_RegisterAccount_Request_21000::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 Login_RegisterAccount_Request_21000::error() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterAccount_Request_21000.Error)
  return error_;
}
inline void Login_RegisterAccount_Request_21000::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:login.Login_RegisterAccount_Request_21000.Error)
}

// -------------------------------------------------------------------

// Login_RegisterAccount_Response_21001

// int32 RpcId = 1;
inline void Login_RegisterAccount_Response_21001::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 Login_RegisterAccount_Response_21001::rpcid() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterAccount_Response_21001.RpcId)
  return rpcid_;
}
inline void Login_RegisterAccount_Response_21001::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:login.Login_RegisterAccount_Response_21001.RpcId)
}

// string Message = 2;
inline void Login_RegisterAccount_Response_21001::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_RegisterAccount_Response_21001::message() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterAccount_Response_21001.Message)
  return message_.GetNoArena();
}
inline void Login_RegisterAccount_Response_21001::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_RegisterAccount_Response_21001.Message)
}
#if LANG_CXX11
inline void Login_RegisterAccount_Response_21001::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:login.Login_RegisterAccount_Response_21001.Message)
}
#endif
inline void Login_RegisterAccount_Response_21001::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_RegisterAccount_Response_21001.Message)
}
inline void Login_RegisterAccount_Response_21001::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_RegisterAccount_Response_21001.Message)
}
inline ::std::string* Login_RegisterAccount_Response_21001::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_RegisterAccount_Response_21001.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_RegisterAccount_Response_21001::release_message() {
  // @@protoc_insertion_point(field_release:login.Login_RegisterAccount_Response_21001.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_RegisterAccount_Response_21001::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:login.Login_RegisterAccount_Response_21001.Message)
}

// int32 Error = 3;
inline void Login_RegisterAccount_Response_21001::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 Login_RegisterAccount_Response_21001::error() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterAccount_Response_21001.Error)
  return error_;
}
inline void Login_RegisterAccount_Response_21001::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:login.Login_RegisterAccount_Response_21001.Error)
}

// -------------------------------------------------------------------

// Login_LoginServer_Request_21002

// string accouent = 1;
inline void Login_LoginServer_Request_21002::clear_accouent() {
  accouent_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_LoginServer_Request_21002::accouent() const {
  // @@protoc_insertion_point(field_get:login.Login_LoginServer_Request_21002.accouent)
  return accouent_.GetNoArena();
}
inline void Login_LoginServer_Request_21002::set_accouent(const ::std::string& value) {
  
  accouent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_LoginServer_Request_21002.accouent)
}
#if LANG_CXX11
inline void Login_LoginServer_Request_21002::set_accouent(::std::string&& value) {
  
  accouent_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:login.Login_LoginServer_Request_21002.accouent)
}
#endif
inline void Login_LoginServer_Request_21002::set_accouent(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  accouent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_LoginServer_Request_21002.accouent)
}
inline void Login_LoginServer_Request_21002::set_accouent(const char* value, size_t size) {
  
  accouent_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_LoginServer_Request_21002.accouent)
}
inline ::std::string* Login_LoginServer_Request_21002::mutable_accouent() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_LoginServer_Request_21002.accouent)
  return accouent_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_LoginServer_Request_21002::release_accouent() {
  // @@protoc_insertion_point(field_release:login.Login_LoginServer_Request_21002.accouent)
  
  return accouent_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_LoginServer_Request_21002::set_allocated_accouent(::std::string* accouent) {
  if (accouent != NULL) {
    
  } else {
    
  }
  accouent_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), accouent);
  // @@protoc_insertion_point(field_set_allocated:login.Login_LoginServer_Request_21002.accouent)
}

// string password = 2;
inline void Login_LoginServer_Request_21002::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_LoginServer_Request_21002::password() const {
  // @@protoc_insertion_point(field_get:login.Login_LoginServer_Request_21002.password)
  return password_.GetNoArena();
}
inline void Login_LoginServer_Request_21002::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_LoginServer_Request_21002.password)
}
#if LANG_CXX11
inline void Login_LoginServer_Request_21002::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:login.Login_LoginServer_Request_21002.password)
}
#endif
inline void Login_LoginServer_Request_21002::set_password(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_LoginServer_Request_21002.password)
}
inline void Login_LoginServer_Request_21002::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_LoginServer_Request_21002.password)
}
inline ::std::string* Login_LoginServer_Request_21002::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_LoginServer_Request_21002.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_LoginServer_Request_21002::release_password() {
  // @@protoc_insertion_point(field_release:login.Login_LoginServer_Request_21002.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_LoginServer_Request_21002::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:login.Login_LoginServer_Request_21002.password)
}

// int32 RpcId = 3;
inline void Login_LoginServer_Request_21002::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 Login_LoginServer_Request_21002::rpcid() const {
  // @@protoc_insertion_point(field_get:login.Login_LoginServer_Request_21002.RpcId)
  return rpcid_;
}
inline void Login_LoginServer_Request_21002::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:login.Login_LoginServer_Request_21002.RpcId)
}

// string Message = 4;
inline void Login_LoginServer_Request_21002::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_LoginServer_Request_21002::message() const {
  // @@protoc_insertion_point(field_get:login.Login_LoginServer_Request_21002.Message)
  return message_.GetNoArena();
}
inline void Login_LoginServer_Request_21002::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_LoginServer_Request_21002.Message)
}
#if LANG_CXX11
inline void Login_LoginServer_Request_21002::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:login.Login_LoginServer_Request_21002.Message)
}
#endif
inline void Login_LoginServer_Request_21002::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_LoginServer_Request_21002.Message)
}
inline void Login_LoginServer_Request_21002::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_LoginServer_Request_21002.Message)
}
inline ::std::string* Login_LoginServer_Request_21002::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_LoginServer_Request_21002.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_LoginServer_Request_21002::release_message() {
  // @@protoc_insertion_point(field_release:login.Login_LoginServer_Request_21002.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_LoginServer_Request_21002::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:login.Login_LoginServer_Request_21002.Message)
}

// int32 Error = 5;
inline void Login_LoginServer_Request_21002::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 Login_LoginServer_Request_21002::error() const {
  // @@protoc_insertion_point(field_get:login.Login_LoginServer_Request_21002.Error)
  return error_;
}
inline void Login_LoginServer_Request_21002::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:login.Login_LoginServer_Request_21002.Error)
}

// -------------------------------------------------------------------

// Login_LoginServer_Response_21003

// int32 SessionID = 1;
inline void Login_LoginServer_Response_21003::clear_sessionid() {
  sessionid_ = 0;
}
inline ::google::protobuf::int32 Login_LoginServer_Response_21003::sessionid() const {
  // @@protoc_insertion_point(field_get:login.Login_LoginServer_Response_21003.SessionID)
  return sessionid_;
}
inline void Login_LoginServer_Response_21003::set_sessionid(::google::protobuf::int32 value) {
  
  sessionid_ = value;
  // @@protoc_insertion_point(field_set:login.Login_LoginServer_Response_21003.SessionID)
}

// int32 RpcId = 2;
inline void Login_LoginServer_Response_21003::clear_rpcid() {
  rpcid_ = 0;
}
inline ::google::protobuf::int32 Login_LoginServer_Response_21003::rpcid() const {
  // @@protoc_insertion_point(field_get:login.Login_LoginServer_Response_21003.RpcId)
  return rpcid_;
}
inline void Login_LoginServer_Response_21003::set_rpcid(::google::protobuf::int32 value) {
  
  rpcid_ = value;
  // @@protoc_insertion_point(field_set:login.Login_LoginServer_Response_21003.RpcId)
}

// string Message = 3;
inline void Login_LoginServer_Response_21003::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_LoginServer_Response_21003::message() const {
  // @@protoc_insertion_point(field_get:login.Login_LoginServer_Response_21003.Message)
  return message_.GetNoArena();
}
inline void Login_LoginServer_Response_21003::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_LoginServer_Response_21003.Message)
}
#if LANG_CXX11
inline void Login_LoginServer_Response_21003::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:login.Login_LoginServer_Response_21003.Message)
}
#endif
inline void Login_LoginServer_Response_21003::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_LoginServer_Response_21003.Message)
}
inline void Login_LoginServer_Response_21003::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_LoginServer_Response_21003.Message)
}
inline ::std::string* Login_LoginServer_Response_21003::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_LoginServer_Response_21003.Message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_LoginServer_Response_21003::release_message() {
  // @@protoc_insertion_point(field_release:login.Login_LoginServer_Response_21003.Message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_LoginServer_Response_21003::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:login.Login_LoginServer_Response_21003.Message)
}

// int32 Error = 4;
inline void Login_LoginServer_Response_21003::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 Login_LoginServer_Response_21003::error() const {
  // @@protoc_insertion_point(field_get:login.Login_LoginServer_Response_21003.Error)
  return error_;
}
inline void Login_LoginServer_Response_21003::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:login.Login_LoginServer_Response_21003.Error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace login

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_login_2eproto__INCLUDED
